/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import com.werzuo.shfcms.controller.BackUpController;
import com.werzuo.shfcms.controllerfactoryimpl.ControllerFactoryImpl;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ravindu
 */
public class BackupPanel extends javax.swing.JPanel {

    /**
     * Creates new form BackupPanel
     */
    private HomeFrame homeFrame;

    public BackupPanel() {
        initComponents();
    }

    BackupPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnCreateBackupImage = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCreateBackuptxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCreateBackup = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblModfyEventBt1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3);
        jLabel3.setBounds(480, 210, 150, 100);

        btnCreateBackupImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCreateBackupImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/backupIco.png"))); // NOI18N
        btnCreateBackupImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateBackupImageMouseClicked(evt);
            }
        });
        add(btnCreateBackupImage);
        btnCreateBackupImage.setBounds(290, 210, 150, 110);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(43, 227, 117));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Manage BackUp");
        add(jLabel8);
        jLabel8.setBounds(730, 0, 240, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Restore Backup");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7);
        jLabel7.setBounds(480, 320, 150, 30);

        btnCreateBackuptxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreateBackuptxt.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateBackuptxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCreateBackuptxt.setText("Create Backup");
        btnCreateBackuptxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateBackuptxtMouseClicked(evt);
            }
        });
        add(btnCreateBackuptxt);
        btnCreateBackuptxt.setBounds(290, 330, 150, 20);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel4);
        jLabel4.setBounds(480, 210, 150, 140);

        btnCreateBackup.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateBackup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCreateBackup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateBackupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateBackupMouseExited(evt);
            }
        });
        add(btnCreateBackup);
        btnCreateBackup.setBounds(290, 210, 150, 140);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 217, 127)));
        add(jLabel5);
        jLabel5.setBounds(130, 130, 680, 310);

        lblModfyEventBt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblModfyEventBt1.setForeground(new java.awt.Color(255, 255, 255));
        lblModfyEventBt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModfyEventBt1.setText("Back");
        lblModfyEventBt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblModfyEventBt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseExited(evt);
            }
        });
        add(lblModfyEventBt1);
        lblModfyEventBt1.setBounds(810, 500, 120, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel2);
        jLabel2.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void lblModfyEventBt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseClicked
        SettingsPanel s = new SettingsPanel();
        homeFrame.panelBody.removeAll();
        s.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.add(s);
        homeFrame.panelBody.revalidate();
        homeFrame.panelBody.repaint();
    }//GEN-LAST:event_lblModfyEventBt1MouseClicked

    private void lblModfyEventBt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt1MouseEntered

    private void lblModfyEventBt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt1MouseExited

    private void btnCreateBackupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateBackupMouseEntered
        btnCreateBackup.setBorder(new LineBorder(new Color(43, 227, 117)));
        btnCreateBackupImage.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/backupIcoGreen.png"));
        btnCreateBackuptxt.setForeground(new Color(43, 227, 117));
    }//GEN-LAST:event_btnCreateBackupMouseEntered

    private void btnCreateBackupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateBackupMouseExited
        btnCreateBackup.setBorder(new LineBorder(Color.WHITE));
        btnCreateBackupImage.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/backupIco.png"));
        btnCreateBackuptxt.setForeground((Color.WHITE));
    }//GEN-LAST:event_btnCreateBackupMouseExited

    private void btnCreateBackupImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateBackupImageMouseClicked
        try {
            createBackUp();
        } catch (InterruptedException ex) {
            Logger.getLogger(BackupPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BackupPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateBackupImageMouseClicked

    private void btnCreateBackuptxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateBackuptxtMouseClicked
        try {
            createBackUp();
        } catch (InterruptedException ex) {
            Logger.getLogger(BackupPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BackupPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCreateBackuptxtMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        try {
            restoreBackUp();
        } catch (InterruptedException ex) {
            Logger.getLogger(BackupPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BackupPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        try {
            restoreBackUp();
        } catch (InterruptedException ex) {
            Logger.getLogger(BackupPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BackupPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel7MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCreateBackup;
    private javax.swing.JLabel btnCreateBackupImage;
    private javax.swing.JLabel btnCreateBackuptxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblModfyEventBt1;
    // End of variables declaration//GEN-END:variables

    /**
     * create the back up of the database SW96
     */
    private void createBackUp() throws InterruptedException, IOException {
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File file = fc.getSelectedFile();
        String path = file.getAbsolutePath();

        BackUpController backUpController = new ControllerFactoryImpl().getBackUpController();
        int restoreBackup = backUpController.writeBackup(path);
        if (restoreBackup == 0) {
            JOptionPane.showMessageDialog(this, "Back Up Success !!");
        } else {
            JOptionPane.showMessageDialog(this, "Back Up Failed !");
        }

    }

    /**
     * restore the created back up file SW96
     */
    private void restoreBackUp() throws InterruptedException, IOException {
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        File file = fc.getSelectedFile();
        String path = file.getAbsolutePath();

        BackUpController backUpController = new ControllerFactoryImpl().getBackUpController();
        int restoreBackup = backUpController.restoreBackup(path);
        if (restoreBackup == 0) {
            JOptionPane.showMessageDialog(this, "Restore Back Up Success !!");
        } else {
            JOptionPane.showMessageDialog(this, "Restore Failed !");
        }
    }
}
