/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import com.werzuo.shfcms.common.Validation;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;

/**
 *
 * @author kaushalya
 */
public class DashBoardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashBoardPanel
     */
    private HomeFrame homeFrame;

    public DashBoardPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;

    }

    public DashBoardPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtWeight = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtBmi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblReminder = new javax.swing.JLabel();
        lblReminderIcon = new javax.swing.JLabel();
        lblReminderTxt = new javax.swing.JLabel();
        lblOnGoing = new javax.swing.JLabel();
        lblOnGoingText = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        lblSearchText = new javax.swing.JLabel();
        lblArrears = new javax.swing.JLabel();
        lblArrearsText = new javax.swing.JLabel();
        lblSchedule = new javax.swing.JLabel();
        lblScheduleText = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblAboutText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 227, 117), 2));
        setLayout(null);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Kg");
        add(jLabel13);
        jLabel13.setBounds(510, 300, 40, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/kgm-2.png"))); // NOI18N
        add(jLabel14);
        jLabel14.setBounds(510, 380, 50, 30);

        txtWeight.setBackground(new java.awt.Color(0, 0, 0));
        txtWeight.setForeground(new java.awt.Color(255, 255, 255));
        txtWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtWeight.setText("0");
        txtWeight.setCaretColor(new java.awt.Color(255, 255, 255));
        txtWeight.setOpaque(false);
        txtWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWeightActionPerformed(evt);
            }
        });
        add(txtWeight);
        txtWeight.setBounds(370, 300, 130, 30);

        txtHeight.setBackground(new java.awt.Color(0, 0, 0));
        txtHeight.setForeground(new java.awt.Color(255, 255, 255));
        txtHeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHeight.setText("0");
        txtHeight.setCaretColor(new java.awt.Color(255, 255, 255));
        txtHeight.setOpaque(false);
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHeightKeyReleased(evt);
            }
        });
        add(txtHeight);
        txtHeight.setBounds(370, 340, 130, 30);

        txtBmi.setEditable(false);
        txtBmi.setBackground(new java.awt.Color(0, 0, 0));
        txtBmi.setForeground(new java.awt.Color(255, 255, 255));
        txtBmi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBmi.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBmi.setOpaque(false);
        txtBmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBmiActionPerformed(evt);
            }
        });
        txtBmi.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtBmiPropertyChange(evt);
            }
        });
        add(txtBmi);
        txtBmi.setBounds(370, 380, 130, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("m");
        add(jLabel15);
        jLabel15.setBounds(510, 340, 30, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("BMI");
        add(jLabel12);
        jLabel12.setBounds(240, 380, 100, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Your Height");
        add(jLabel11);
        jLabel11.setBounds(240, 340, 100, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Your Weight");
        add(jLabel10);
        jLabel10.setBounds(240, 300, 100, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(43, 227, 117));
        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "BMI Meter", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(43, 217, 127))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(230, 250, 330, 172);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(43, 217, 127));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("0777123456");
        add(jLabel7);
        jLabel7.setBounds(710, 500, 220, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(43, 217, 127));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Matara");
        add(jLabel6);
        jLabel6.setBounds(710, 470, 220, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(43, 217, 127));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Polhena");
        add(jLabel5);
        jLabel5.setBounds(710, 440, 220, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(43, 217, 127));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Super Hero Fitness Center");
        add(jLabel4);
        jLabel4.setBounds(710, 410, 220, 40);

        lblReminder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReminder.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblReminder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblReminder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReminderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReminderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReminderMouseExited(evt);
            }
        });
        add(lblReminder);
        lblReminder.setBounds(50, 260, 150, 160);

        lblReminderIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReminderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/hhWhite_2.png"))); // NOI18N
        add(lblReminderIcon);
        lblReminderIcon.setBounds(60, 260, 130, 120);

        lblReminderTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReminderTxt.setForeground(new java.awt.Color(255, 255, 255));
        lblReminderTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReminderTxt.setText("Birth day Reminder");
        add(lblReminderTxt);
        lblReminderTxt.setBounds(50, 380, 150, 30);

        lblOnGoing.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOnGoing.setForeground(new java.awt.Color(255, 255, 255));
        lblOnGoing.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOnGoing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/on Going Player.png"))); // NOI18N
        lblOnGoing.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblOnGoing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblOnGoing.setIconTextGap(8);
        lblOnGoing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOnGoingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOnGoingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOnGoingMouseExited(evt);
            }
        });
        add(lblOnGoing);
        lblOnGoing.setBounds(50, 70, 150, 160);

        lblOnGoingText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblOnGoingText.setForeground(new java.awt.Color(255, 255, 255));
        lblOnGoingText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOnGoingText.setText("On Going Players");
        add(lblOnGoingText);
        lblOnGoingText.setBounds(50, 200, 150, 30);

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/5white.png"))); // NOI18N
        lblSearch.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSearchMouseExited(evt);
            }
        });
        add(lblSearch);
        lblSearch.setBounds(230, 70, 150, 160);

        lblSearchText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSearchText.setForeground(new java.awt.Color(255, 255, 255));
        lblSearchText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchText.setText("Search Member");
        add(lblSearchText);
        lblSearchText.setBounds(230, 200, 150, 30);

        lblArrears.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblArrears.setForeground(new java.awt.Color(255, 255, 255));
        lblArrears.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArrears.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/4White.png"))); // NOI18N
        lblArrears.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblArrears.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblArrears.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblArrearsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblArrearsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblArrearsMouseExited(evt);
            }
        });
        add(lblArrears);
        lblArrears.setBounds(410, 70, 150, 160);

        lblArrearsText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblArrearsText.setForeground(new java.awt.Color(255, 255, 255));
        lblArrearsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArrearsText.setText("Payment Arrears");
        add(lblArrearsText);
        lblArrearsText.setBounds(410, 200, 150, 30);

        lblSchedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lblSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/3.png"))); // NOI18N
        lblSchedule.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSchedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblScheduleMouseExited(evt);
            }
        });
        add(lblSchedule);
        lblSchedule.setBounds(590, 70, 150, 160);

        lblScheduleText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblScheduleText.setForeground(new java.awt.Color(255, 255, 255));
        lblScheduleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScheduleText.setText("Schedule Updation");
        add(lblScheduleText);
        lblScheduleText.setBounds(590, 200, 150, 30);

        lblAbout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(255, 255, 255));
        lblAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/2_1.png"))); // NOI18N
        lblAbout.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblAbout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAboutMouseExited(evt);
            }
        });
        add(lblAbout);
        lblAbout.setBounds(770, 70, 150, 160);

        lblAboutText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAboutText.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAboutText.setText("About");
        add(lblAboutText);
        lblAboutText.setBounds(770, 200, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 227, 117));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dashboard");
        add(jLabel2);
        jLabel2.setBounds(820, 0, 150, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel3);
        jLabel3.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void lblOnGoingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOnGoingMouseEntered
        lblOnGoing.setBorder(new LineBorder(new Color(43, 227, 117)));
        lblOnGoingText.setForeground(new Color(43, 227, 117));
        lblOnGoing.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/1green.png"));
    }//GEN-LAST:event_lblOnGoingMouseEntered

    private void lblOnGoingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOnGoingMouseExited
        lblOnGoing.setBorder(new LineBorder(Color.WHITE));
        lblOnGoingText.setForeground(Color.WHITE);
        lblOnGoing.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/on Going Player.png"));
    }//GEN-LAST:event_lblOnGoingMouseExited

    private void lblSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseEntered
        lblSearch.setBorder(new LineBorder(new Color(43, 227, 117)));
        lblSearchText.setForeground(new Color(43, 227, 117));
        lblSearch.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/5green.png"));
    }//GEN-LAST:event_lblSearchMouseEntered

    private void lblSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseExited
        lblSearch.setBorder(new LineBorder(Color.WHITE));
        lblSearchText.setForeground(Color.WHITE);
        lblSearch.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/5white.png"));
    }//GEN-LAST:event_lblSearchMouseExited

    private void lblScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseEntered
        lblSchedule.setBorder(new LineBorder(new Color(43, 227, 117)));
        lblScheduleText.setForeground(new Color(43, 227, 117));
        lblSchedule.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/3green.png"));
    }//GEN-LAST:event_lblScheduleMouseEntered

    private void lblScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseExited
        lblSchedule.setBorder(new LineBorder(Color.WHITE));
        lblScheduleText.setForeground(Color.WHITE);
        lblSchedule.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/3.png"));
    }//GEN-LAST:event_lblScheduleMouseExited

    private void lblAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseEntered
        lblAbout.setBorder(new LineBorder(new Color(43, 227, 117)));
        lblAboutText.setForeground(new Color(43, 227, 117));
        lblAbout.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/2green.png"));
    }//GEN-LAST:event_lblAboutMouseEntered

    private void lblAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseExited
        lblAbout.setBorder(new LineBorder(Color.WHITE));
        lblAboutText.setForeground(Color.WHITE);
        lblAbout.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/2_1.png"));
    }//GEN-LAST:event_lblAboutMouseExited

    private void lblArrearsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArrearsMouseEntered
        lblArrears.setBorder(new LineBorder(new Color(43, 227, 117)));
        lblArrearsText.setForeground(new Color(43, 227, 117));
        lblArrears.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/4green.png"));
    }//GEN-LAST:event_lblArrearsMouseEntered

    private void lblArrearsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArrearsMouseExited
        lblArrears.setBorder(new LineBorder(Color.WHITE));
        lblArrearsText.setForeground(Color.WHITE);
        lblArrears.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/4White.png"));
    }//GEN-LAST:event_lblArrearsMouseExited

    private void lblReminderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReminderMouseEntered
        lblReminder.setBorder(new LineBorder(new Color(43, 227, 117)));
        lblReminderTxt.setForeground(new Color(43, 227, 117));
        lblReminderIcon.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/hhGreen_2.png"));
    }//GEN-LAST:event_lblReminderMouseEntered

    private void lblReminderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReminderMouseExited
        lblReminder.setBorder(new LineBorder(Color.WHITE));
        lblReminderTxt.setForeground(Color.WHITE);
        lblReminderIcon.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/hhWhite_2.png"));

    }//GEN-LAST:event_lblReminderMouseExited

    private void txtWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWeightActionPerformed
        txtHeight.requestFocus();
        if(txtWeight.getText().isEmpty()){
            txtWeight.setText("0");
        }
    }//GEN-LAST:event_txtWeightActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        if(txtHeight.getText().isEmpty()){
            txtHeight.setText("0");
        }
        Double height = Double.parseDouble(txtHeight.getText());
        Double Weight = Double.parseDouble(txtWeight.getText());
        
        
        Double bmi = Weight / (height * height);
        System.out.println(bmi);
        String data = String.format("%.2f", bmi);
        txtBmi.setText(data );

        String bmit = txtBmi.getText();
        if (!bmit.isEmpty()) {
            boolean res = bmit.matches("[0-9]+[.]?[0-9]{0,3}");
            if (!res) {
                txtBmi.setText(bmit.substring(0, bmit.length() - 1));
            }
        }

    }//GEN-LAST:event_txtHeightActionPerformed

    private void lblOnGoingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOnGoingMouseClicked
        OnGoingPlyersPanel a = new OnGoingPlyersPanel(homeFrame);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblOnGoingMouseClicked

    private void txtBmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBmiActionPerformed


    }//GEN-LAST:event_txtBmiActionPerformed

    private void txtHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyReleased


    }//GEN-LAST:event_txtHeightKeyReleased

    private void txtBmiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtBmiPropertyChange

    }//GEN-LAST:event_txtBmiPropertyChange

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        SearchMemberPanel a = new SearchMemberPanel(homeFrame);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblSearchMouseClicked

    private void lblArrearsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblArrearsMouseClicked
        PaymentArriousPanel a = new PaymentArriousPanel(homeFrame);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblArrearsMouseClicked

    private void lblScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseClicked
        SchedulePanel a = new SchedulePanel(homeFrame);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblScheduleMouseClicked

    private void lblAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseClicked
        AboutSoftWarePanel a = new AboutSoftWarePanel(homeFrame);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblAboutMouseClicked

    private void lblReminderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReminderMouseClicked
        BirthDayRiminderPanel a = new BirthDayRiminderPanel(homeFrame);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblReminderMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAboutText;
    private javax.swing.JLabel lblArrears;
    private javax.swing.JLabel lblArrearsText;
    private javax.swing.JLabel lblOnGoing;
    private javax.swing.JLabel lblOnGoingText;
    private javax.swing.JLabel lblReminder;
    private javax.swing.JLabel lblReminderIcon;
    private javax.swing.JLabel lblReminderTxt;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblScheduleText;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSearchText;
    private javax.swing.JTextField txtBmi;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
