/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.border.LineBorder;

/**
 *
 * @author Deshaa
 */
public class HomeFrame extends javax.swing.JFrame {

    public static String userName;
    private JLabel clickedLabel;
    private String clickedImage;
    private int clickedsideLbl;
    public static HomeFrame homeFrame;
    public static MemberRegPanel mrp;

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
       // panelBody.setBackground(new Color(0, 0, 0, 127));
        labelVisibleFalse();

        clickedLabel = lblDashboard;
        clickedsideLbl = 1;
        clickedImage = "./src/com/werzuo/shfcms/images/dashboardIco.png";
        lblDashboard.setForeground(new Color(43, 227, 117));
        lblDashboard.setBorder(new LineBorder(new Color(43, 227, 117), 2));
        lblDashboard.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/dashboardIcoSel.png"));
        setSideLabes();

        DashBoardPanel d = new DashBoardPanel();
        panelBody.removeAll();
        d.setSize(panelBody.getSize());
        panelBody.add(d);
        panelBody.revalidate();
        panelBody.repaint();
        homeFrame = this;
        setDate();
        setTime();

    }

    public HomeFrame(String userName) {
        initComponents();
        //panelBody.setBackground(new Color(0, 0, 0, 127));
        this.userName = userName;
        labelVisibleFalse();

        clickedLabel = lblDashboard;
        clickedsideLbl = 1;
        clickedImage = "./src/com/werzuo/shfcms/images/dashboardIco.png";
        lblDashboard.setForeground(new Color(43, 227, 117));
        lblDashboard.setBorder(new LineBorder(new Color(43, 227, 117), 2));
        lblDashboard.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/dashboardIcoSel.png"));
        setSideLabes();

        DashBoardPanel d = new DashBoardPanel();
        panelBody.removeAll();
        d.setSize(panelBody.getSize());
        panelBody.add(d);
        panelBody.revalidate();
        panelBody.repaint();

        homeFrame = this;
        setDate();
        setTime();

    }

    /**
     * set the date to the label
     */
    private void setDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        dateL.setText(s.format(d));
    }

    /**
     * set the time to the label
     */
    private void setTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                timeL.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        dateL = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        timeL = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        lblCloseBt = new javax.swing.JLabel();
        lblMaximizeBt = new javax.swing.JLabel();
        lblMinimizeBt = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        lblAttendance = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        lblMember = new javax.swing.JLabel();
        lblSchedule = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        lblSettings = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel2.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel2.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel2.setLayout(null);

        l1.setBackground(new java.awt.Color(43, 227, 117));
        l1.setOpaque(true);
        jPanel2.add(l1);
        l1.setBounds(310, 150, 30, 50);

        l2.setBackground(new java.awt.Color(43, 227, 117));
        l2.setOpaque(true);
        jPanel2.add(l2);
        l2.setBounds(310, 230, 30, 50);

        l3.setBackground(new java.awt.Color(43, 227, 117));
        l3.setOpaque(true);
        jPanel2.add(l3);
        l3.setBounds(310, 310, 30, 50);

        dateL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dateL.setForeground(new java.awt.Color(255, 255, 255));
        dateL.setText("adssadasds");
        jPanel2.add(dateL);
        dateL.setBounds(120, 10, 100, 30);

        l4.setBackground(new java.awt.Color(43, 227, 117));
        l4.setOpaque(true);
        jPanel2.add(l4);
        l4.setBounds(310, 390, 30, 50);

        l5.setBackground(new java.awt.Color(43, 227, 117));
        l5.setOpaque(true);
        jPanel2.add(l5);
        l5.setBounds(310, 470, 30, 50);

        l6.setBackground(new java.awt.Color(43, 227, 117));
        l6.setOpaque(true);
        jPanel2.add(l6);
        l6.setBounds(310, 550, 30, 50);

        timeL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        timeL.setForeground(new java.awt.Color(255, 255, 255));
        timeL.setText("dasdasdsd");
        jPanel2.add(timeL);
        timeL.setBounds(220, 10, 100, 30);

        l7.setBackground(new java.awt.Color(43, 227, 117));
        l7.setOpaque(true);
        jPanel2.add(l7);
        l7.setBounds(310, 630, 30, 50);

        lblCloseBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/close.png"))); // NOI18N
        lblCloseBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseBtMouseExited(evt);
            }
        });
        jPanel2.add(lblCloseBt);
        lblCloseBt.setBounds(20, 10, 30, 30);

        lblMaximizeBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaximizeBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Maximize.png"))); // NOI18N
        lblMaximizeBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMaximizeBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMaximizeBtMouseExited(evt);
            }
        });
        jPanel2.add(lblMaximizeBt);
        lblMaximizeBt.setBounds(70, 10, 30, 30);

        lblMinimizeBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizeBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/mimimize.png"))); // NOI18N
        lblMinimizeBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeBtMouseExited(evt);
            }
        });
        jPanel2.add(lblMinimizeBt);
        lblMinimizeBt.setBounds(50, 10, 20, 30);

        lblDashboard.setBackground(new java.awt.Color(47, 227, 117));
        lblDashboard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/dashboardIco.png"))); // NOI18N
        lblDashboard.setText("     Dashboard");
        lblDashboard.setAlignmentY(0.6F);
        lblDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDashboardMouseExited(evt);
            }
        });
        jPanel2.add(lblDashboard);
        lblDashboard.setBounds(80, 150, 230, 50);

        lblAttendance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAttendance.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/attendance.png"))); // NOI18N
        lblAttendance.setText("    Attendance");
        lblAttendance.setAlignmentY(0.6F);
        lblAttendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAttendanceMouseExited(evt);
            }
        });
        jPanel2.add(lblAttendance);
        lblAttendance.setBounds(80, 230, 230, 50);

        lblPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/payment.png"))); // NOI18N
        lblPayment.setText("      Payment   ");
        lblPayment.setAlignmentY(0.6F);
        lblPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPaymentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPaymentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPaymentMouseExited(evt);
            }
        });
        jPanel2.add(lblPayment);
        lblPayment.setBounds(80, 310, 230, 50);

        lblMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMember.setForeground(new java.awt.Color(255, 255, 255));
        lblMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/member.png"))); // NOI18N
        lblMember.setText("      Member    ");
        lblMember.setAlignmentY(0.6F);
        lblMember.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMemberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMemberMouseExited(evt);
            }
        });
        jPanel2.add(lblMember);
        lblMember.setBounds(80, 390, 230, 50);

        lblSchedule.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSchedule.setForeground(new java.awt.Color(255, 255, 255));
        lblSchedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchedule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/schedule.png"))); // NOI18N
        lblSchedule.setText("      Schedule   ");
        lblSchedule.setAlignmentY(0.6F);
        lblSchedule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblScheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblScheduleMouseExited(evt);
            }
        });
        jPanel2.add(lblSchedule);
        lblSchedule.setBounds(80, 470, 230, 50);

        lblReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblReport.setForeground(new java.awt.Color(255, 255, 255));
        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/reports.png"))); // NOI18N
        lblReport.setText("        Report     ");
        lblReport.setAlignmentY(0.6F);
        lblReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportMouseExited(evt);
            }
        });
        jPanel2.add(lblReport);
        lblReport.setBounds(80, 550, 230, 50);

        lblSettings.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSettings.setForeground(new java.awt.Color(255, 255, 255));
        lblSettings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/settings.png"))); // NOI18N
        lblSettings.setText("      Settings    ");
        lblSettings.setAlignmentY(0.6F);
        lblSettings.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSettingsMouseExited(evt);
            }
        });
        jPanel2.add(lblSettings);
        lblSettings.setBounds(80, 630, 230, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/logo.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(1110, 10, 210, 110);

        panelBody.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 227, 117), 2));

        javax.swing.GroupLayout panelBodyLayout = new javax.swing.GroupLayout(panelBody);
        panelBody.setLayout(panelBodyLayout);
        panelBodyLayout.setHorizontalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 966, Short.MAX_VALUE)
        );
        panelBodyLayout.setVerticalGroup(
            panelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        jPanel2.add(panelBody);
        panelBody.setBounds(340, 130, 970, 570);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(60, 130, 270, 570);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/home background image.png"))); // NOI18N
        jLabel2.setAlignmentY(0.6F);
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setMaximumSize(new java.awt.Dimension(1368, 160));
        jLabel2.setMinimumSize(new java.awt.Dimension(1368, 160));
        jLabel2.setPreferredSize(new java.awt.Dimension(1368, 160));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(40, 54, 340, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseEntered

    }//GEN-LAST:event_lblDashboardMouseEntered

    private void lblDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseExited

    }//GEN-LAST:event_lblDashboardMouseExited

    private void lblAttendanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseEntered

    }//GEN-LAST:event_lblAttendanceMouseEntered

    private void lblAttendanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseExited

    }//GEN-LAST:event_lblAttendanceMouseExited

    private void lblMemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberMouseEntered

    }//GEN-LAST:event_lblMemberMouseEntered

    private void lblMemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberMouseExited

    }//GEN-LAST:event_lblMemberMouseExited

    private void lblScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseEntered

    }//GEN-LAST:event_lblScheduleMouseEntered

    private void lblScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseExited

    }//GEN-LAST:event_lblScheduleMouseExited

    private void lblReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseEntered

    }//GEN-LAST:event_lblReportMouseEntered

    private void lblReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseExited

    }//GEN-LAST:event_lblReportMouseExited

    private void lblSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseEntered

    }//GEN-LAST:event_lblSettingsMouseEntered

    private void lblSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseExited

    }//GEN-LAST:event_lblSettingsMouseExited

    private void lblPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseClicked
        if (mrp != null) {
            mrp.stopcam();
        }
        PaymentPanel p = new PaymentPanel();
        panelBody.removeAll();
        p.setSize(panelBody.getSize());
        panelBody.add(p);
        panelBody.revalidate();
        panelBody.repaint();

        setLabelColors(lblPayment, "./src/com/werzuo/shfcms/images/paymentSel.png");
        clickedLabel = lblPayment;
        clickedImage = "./src/com/werzuo/shfcms/images/payment.png";
        clickedsideLbl = 3;
        setSideLabes();
    }//GEN-LAST:event_lblPaymentMouseClicked

    private void lblPaymentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseEntered

    }//GEN-LAST:event_lblPaymentMouseEntered

    private void lblPaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPaymentMouseExited

    }//GEN-LAST:event_lblPaymentMouseExited

    private void lblCloseBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseBtMouseEntered
        lblCloseBt.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/closeFill.png"));
    }//GEN-LAST:event_lblCloseBtMouseEntered

    private void lblCloseBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseBtMouseExited
        lblCloseBt.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/close.png"));
    }//GEN-LAST:event_lblCloseBtMouseExited

    private void lblMinimizeBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeBtMouseEntered
        lblMinimizeBt.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/mimimizeFill.png"));
    }//GEN-LAST:event_lblMinimizeBtMouseEntered

    private void lblMinimizeBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeBtMouseExited
        lblMinimizeBt.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/mimimize.png"));
    }//GEN-LAST:event_lblMinimizeBtMouseExited

    private void lblMaximizeBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizeBtMouseEntered
        lblMaximizeBt.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/MaximizeFill.png"));
    }//GEN-LAST:event_lblMaximizeBtMouseEntered

    private void lblMaximizeBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizeBtMouseExited
        lblMaximizeBt.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/Maximize.png"));
    }//GEN-LAST:event_lblMaximizeBtMouseExited

    private void lblCloseBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseBtMouseClicked
        // new OptionFrame(this, true, this, "DO YOU WANT TO LOG OUT ?").setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_lblCloseBtMouseClicked

    private void lblMinimizeBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeBtMouseClicked
        setExtendedState(HomeFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeBtMouseClicked

    private void lblAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendanceMouseClicked
        if (mrp != null) {
            mrp.stopcam();
        }
        AttendancePanel a = new AttendancePanel();
        panelBody.removeAll();
        a.setSize(panelBody.getSize());
        panelBody.add(a);
        panelBody.revalidate();
        panelBody.repaint();

        setLabelColors(lblAttendance, "./src/com/werzuo/shfcms/images/attendanceSel.png");
        clickedLabel = lblAttendance;
        clickedImage = "./src/com/werzuo/shfcms/images/attendance.png";
        clickedsideLbl = 2;
        setSideLabes();
    }//GEN-LAST:event_lblAttendanceMouseClicked

    private void lblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardMouseClicked
        if (mrp != null) {
            mrp.stopcam();
        }
        DashBoardPanel d = new DashBoardPanel();
        panelBody.removeAll();
        d.setSize(panelBody.getSize());
        panelBody.add(d);
        panelBody.revalidate();
        panelBody.repaint();

        setLabelColors(lblDashboard, "./src/com/werzuo/shfcms/images/dashboardIcoSel.png");
        clickedLabel = lblDashboard;
        clickedImage = "./src/com/werzuo/shfcms/images/dashboardIco.png";
        clickedsideLbl = 1;
        setSideLabes();
    }//GEN-LAST:event_lblDashboardMouseClicked

    private void lblMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMemberMouseClicked

        MemberRegPanel m = new MemberRegPanel(this);
        mrp = m;
        panelBody.removeAll();
        m.setSize(panelBody.getSize());
        panelBody.add(m);
        panelBody.revalidate();
        panelBody.repaint();

        setLabelColors(lblMember, "./src/com/werzuo/shfcms/images/memberSel.png");
        clickedLabel = lblMember;
        clickedImage = "./src/com/werzuo/shfcms/images/member.png";
        clickedsideLbl = 4;
        setSideLabes();
    }//GEN-LAST:event_lblMemberMouseClicked

    private void lblScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblScheduleMouseClicked
        SchedulePanel s = new SchedulePanel(this);
        if (mrp != null) {
            mrp.stopcam();
        }
        panelBody.removeAll();
        s.setSize(panelBody.getSize());
        panelBody.add(s);
        panelBody.revalidate();
        panelBody.repaint();

        setLabelColors(lblSchedule, "./src/com/werzuo/shfcms/images/scheduleSel.png");
        clickedLabel = lblSchedule;
        clickedImage = "./src/com/werzuo/shfcms/images/schedule.png";
        clickedsideLbl = 5;
        setSideLabes();
    }//GEN-LAST:event_lblScheduleMouseClicked

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        if (mrp != null) {
            mrp.stopcam();
        }
        ReportPanel r = new ReportPanel(this);
        panelBody.removeAll();
        r.setSize(panelBody.getSize());
        panelBody.add(r);
        panelBody.revalidate();
        panelBody.repaint();

        setLabelColors(lblReport, "./src/com/werzuo/shfcms/images/reportsSel.png");
        clickedLabel = lblReport;
        clickedImage = "./src/com/werzuo/shfcms/images/reports.png";
        clickedsideLbl = 6;
        setSideLabes();
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingsMouseClicked
        if (mrp != null) {
            mrp.stopcam();
        }
        SettingsPanel s = new SettingsPanel();
        panelBody.removeAll();
        s.setSize(panelBody.getSize());
        panelBody.add(s);
        panelBody.revalidate();
        panelBody.repaint();

        setLabelColors(lblSettings, "./src/com/werzuo/shfcms/images/settingsSel.png");
        clickedLabel = lblSettings;
        clickedImage = "./src/com/werzuo/shfcms/images/settings.png";
        clickedsideLbl = 7;
        setSideLabes();
    }//GEN-LAST:event_lblSettingsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel dateL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel lblAttendance;
    private javax.swing.JLabel lblCloseBt;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblMaximizeBt;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblMinimizeBt;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblSchedule;
    private javax.swing.JLabel lblSettings;
    public static javax.swing.JPanel panelBody;
    public static javax.swing.JLabel timeL;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param newClicedLabel
     * @param newClickedImage
     */
    public void setLabelColors(JLabel newClicedLabel, String newClickedImage) {
        clickedLabel.setForeground(Color.WHITE);
        clickedLabel.setBorder(new LineBorder(Color.WHITE));
        clickedLabel.setIcon(new ImageIcon(clickedImage));

        newClicedLabel.setForeground(new Color(43, 227, 117));
        newClicedLabel.setBorder(new LineBorder(new Color(43, 227, 117), 2));
        newClicedLabel.setIcon(new ImageIcon(newClickedImage));
    }

    /**
     *
     */
    public void setSideLabes() {
        switch (clickedsideLbl) {
            case 1:
                l1.setVisible(true);
                l2.setVisible(false);
                l3.setVisible(false);
                l4.setVisible(false);
                l5.setVisible(false);
                l6.setVisible(false);
                l7.setVisible(false);
                break;
            case 2:
                l1.setVisible(false);
                l2.setVisible(true);
                l3.setVisible(false);
                l4.setVisible(false);
                l5.setVisible(false);
                l6.setVisible(false);
                l7.setVisible(false);
                break;
            case 3:
                l1.setVisible(false);
                l2.setVisible(false);
                l3.setVisible(true);
                l4.setVisible(false);
                l5.setVisible(false);
                l6.setVisible(false);
                l7.setVisible(false);
                break;
            case 4:
                l1.setVisible(false);
                l2.setVisible(false);
                l3.setVisible(false);
                l4.setVisible(true);
                l5.setVisible(false);
                l6.setVisible(false);
                l7.setVisible(false);
                break;
            case 5:
                l1.setVisible(false);
                l2.setVisible(false);
                l3.setVisible(false);
                l4.setVisible(false);
                l5.setVisible(true);
                l6.setVisible(false);
                l7.setVisible(false);
                break;
            case 6:
                l1.setVisible(false);
                l2.setVisible(false);
                l3.setVisible(false);
                l4.setVisible(false);
                l5.setVisible(false);
                l6.setVisible(true);
                l7.setVisible(false);
                break;
            case 7:
                l1.setVisible(false);
                l2.setVisible(false);
                l3.setVisible(false);
                l4.setVisible(false);
                l5.setVisible(false);
                l6.setVisible(false);
                l7.setVisible(true);
                break;

        }
    }

    /**
     * set the label's false inside the constructor
     */
    private void labelVisibleFalse() {
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l7.setVisible(false);
    }

    /**
     * get date
     *
     * @return date
     */
    public static String getDate() {

        String date = dateL.getText();

        return date;
    }

    /**
     * get time
     *
     * @return time
     */
    public static String getTime() {

        String time = timeL.getText();

        return time;
    }
}
