/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import com.werzuo.shfcms.common.BirthDetails;
import com.werzuo.shfcms.common.Validation;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JSpinner;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ravindu
 */
public class ManageMemberPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMemberPanel
     */
    private HomeFrame homeFrame;

    public ManageMemberPanel() {
        initComponents();
    }

    ManageMemberPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModfyEventBt2 = new javax.swing.JLabel();
        lblCancleEventBt1 = new javax.swing.JLabel();
        txtFname1 = new javax.swing.JTextField();
        lblModfyEventBt = new javax.swing.JLabel();
        lblCancleEventBt = new javax.swing.JLabel();
        lblModfyEventBt1 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtOcc = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        txtFb = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        spinAge = new javax.swing.JSpinner();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        camPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        lblModfyEventBt2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModfyEventBt2.setForeground(new java.awt.Color(255, 255, 255));
        lblModfyEventBt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModfyEventBt2.setText("Browse");
        lblModfyEventBt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblModfyEventBt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModfyEventBt2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModfyEventBt2MouseExited(evt);
            }
        });
        add(lblModfyEventBt2);
        lblModfyEventBt2.setBounds(620, 290, 130, 40);

        lblCancleEventBt1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCancleEventBt1.setForeground(new java.awt.Color(255, 255, 255));
        lblCancleEventBt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancleEventBt1.setText("Capture");
        lblCancleEventBt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblCancleEventBt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancleEventBt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancleEventBt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancleEventBt1MouseExited(evt);
            }
        });
        add(lblCancleEventBt1);
        lblCancleEventBt1.setBounds(760, 290, 130, 40);

        txtFname1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname1.setForeground(new java.awt.Color(255, 255, 255));
        txtFname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname1.setOpaque(false);
        txtFname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFname1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFname1KeyReleased(evt);
            }
        });
        add(txtFname1);
        txtFname1.setBounds(180, 60, 300, 30);

        lblModfyEventBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModfyEventBt.setForeground(new java.awt.Color(255, 255, 255));
        lblModfyEventBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModfyEventBt.setText("Remove Member");
        lblModfyEventBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblModfyEventBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModfyEventBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModfyEventBtMouseExited(evt);
            }
        });
        add(lblModfyEventBt);
        lblModfyEventBt.setBounds(530, 500, 130, 40);

        lblCancleEventBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCancleEventBt.setForeground(new java.awt.Color(255, 255, 255));
        lblCancleEventBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancleEventBt.setText("Modify Member");
        lblCancleEventBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblCancleEventBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancleEventBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancleEventBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancleEventBtMouseExited(evt);
            }
        });
        add(lblCancleEventBt);
        lblCancleEventBt.setBounds(670, 500, 130, 40);

        lblModfyEventBt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblModfyEventBt1.setForeground(new java.awt.Color(255, 255, 255));
        lblModfyEventBt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModfyEventBt1.setText("Back");
        lblModfyEventBt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblModfyEventBt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseExited(evt);
            }
        });
        add(lblModfyEventBt1);
        lblModfyEventBt1.setBounds(810, 500, 120, 40);

        txtFname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname.setForeground(new java.awt.Color(255, 255, 255));
        txtFname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname.setOpaque(false);
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
        });
        add(txtFname);
        txtFname.setBounds(180, 110, 300, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Member ID");
        add(jLabel9);
        jLabel9.setBounds(40, 60, 100, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("First Name");
        add(jLabel11);
        jLabel11.setBounds(40, 110, 110, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Last Name");
        add(jLabel13);
        jLabel13.setBounds(40, 160, 100, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Phone no.");
        add(jLabel17);
        jLabel17.setBounds(40, 210, 110, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Occupation");
        add(jLabel15);
        jLabel15.setBounds(40, 260, 100, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("N.I.C.");
        add(jLabel20);
        jLabel20.setBounds(40, 310, 110, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Address");
        add(jLabel30);
        jLabel30.setBounds(40, 360, 80, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Facebook");
        add(jLabel29);
        jLabel29.setBounds(40, 460, 100, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Email");
        add(jLabel24);
        jLabel24.setBounds(40, 510, 100, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        add(jLabel23);
        jLabel23.setBounds(160, 510, 10, 24);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(":");
        add(jLabel32);
        jLabel32.setBounds(160, 460, 10, 24);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
        add(jLabel31);
        jLabel31.setBounds(160, 360, 10, 24);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        add(jLabel19);
        jLabel19.setBounds(160, 310, 10, 24);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        add(jLabel16);
        jLabel16.setBounds(160, 260, 10, 24);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        add(jLabel18);
        jLabel18.setBounds(160, 210, 10, 24);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        add(jLabel14);
        jLabel14.setBounds(160, 160, 10, 24);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        add(jLabel12);
        jLabel12.setBounds(160, 110, 10, 24);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        add(jLabel10);
        jLabel10.setBounds(160, 60, 10, 24);

        txtLName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtLName.setForeground(new java.awt.Color(255, 255, 255));
        txtLName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtLName.setOpaque(false);
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLNameKeyReleased(evt);
            }
        });
        add(txtLName);
        txtLName.setBounds(180, 160, 300, 30);

        txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhone.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPhone.setOpaque(false);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        add(txtPhone);
        txtPhone.setBounds(180, 210, 300, 30);

        txtOcc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtOcc.setForeground(new java.awt.Color(255, 255, 255));
        txtOcc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOcc.setCaretColor(new java.awt.Color(255, 255, 255));
        txtOcc.setOpaque(false);
        txtOcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOccKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOccKeyReleased(evt);
            }
        });
        add(txtOcc);
        txtOcc.setBounds(180, 260, 300, 30);

        txtNic.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNic.setForeground(new java.awt.Color(255, 255, 255));
        txtNic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNic.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNic.setOpaque(false);
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });
        add(txtNic);
        txtNic.setBounds(180, 310, 300, 30);

        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);

        txtAddress.setBackground(new Color(0,0,0,0));
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setRows(3);
        txtAddress.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAddress.setOpaque(false);
        jScrollPane1.setViewportView(txtAddress);

        add(jScrollPane1);
        jScrollPane1.setBounds(180, 360, 300, 70);
        jScrollPane1.getViewport().setOpaque(false);

        txtFb.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFb.setForeground(new java.awt.Color(255, 255, 255));
        txtFb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFb.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFb.setOpaque(false);
        add(txtFb);
        txtFb.setBounds(180, 460, 300, 30);

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.setOpaque(false);
        add(txtEmail);
        txtEmail.setBounds(180, 510, 300, 30);

        spinAge.setOpaque(false);
        add(spinAge);
        spinAge.setBounds(740, 440, 190, 30);
        spinAge.setOpaque(false);
        spinAge.getEditor().setOpaque(false);
        ((JSpinner.DefaultEditor)spinAge.getEditor()).getTextField().setOpaque(false);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
        add(jLabel25);
        jLabel25.setBounds(710, 440, 10, 24);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Age");
        add(jLabel26);
        jLabel26.setBounds(590, 440, 110, 30);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("D.O.B.");
        add(jLabel27);
        jLabel27.setBounds(590, 390, 100, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(":");
        add(jLabel28);
        jLabel28.setBounds(710, 390, 10, 24);

        txtDob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDob.setForeground(new java.awt.Color(255, 255, 255));
        txtDob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDob.setOpaque(false);
        add(txtDob);
        txtDob.setBounds(740, 390, 190, 30);

        rbMale.setBackground(new Color(0,0,0,0));
        rbMale.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        rbMale.setForeground(new java.awt.Color(255, 255, 255));
        rbMale.setText("Male");
        rbMale.setContentAreaFilled(false);
        add(rbMale);
        rbMale.setBounds(740, 340, 80, 33);

        rbFemale.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbFemale.setText("Female");
        rbFemale.setContentAreaFilled(false);
        add(rbFemale);
        rbFemale.setBounds(830, 340, 100, 33);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":");
        add(jLabel22);
        jLabel22.setBounds(710, 340, 10, 24);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gender");
        add(jLabel21);
        jLabel21.setBounds(590, 340, 100, 30);

        camPanel.setBackground(new java.awt.Color(0, 0, 0));
        camPanel.setForeground(new java.awt.Color(102, 102, 102));
        add(camPanel);
        camPanel.setBounds(600, 70, 320, 210);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 227, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Member");
        add(jLabel3);
        jLabel3.setBounds(700, 0, 270, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel2);
        jLabel2.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtFname);
        }
    }//GEN-LAST:event_txtFnameKeyPressed

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtFname);
        }
    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtLNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtLName);
        }
    }//GEN-LAST:event_txtLNameKeyPressed

    private void txtLNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameKeyReleased

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.phoneNumber(txtPhone);
        }
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.phoneNumber(txtPhone);
        }
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtOccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOccKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtOcc);
        }
    }//GEN-LAST:event_txtOccKeyPressed

    private void txtOccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOccKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtOcc);
        }
    }//GEN-LAST:event_txtOccKeyReleased

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        String id = txtNic.getText();
        txtNic.setForeground(Color.WHITE);
        if (id.length() == 10 | id.length() == 12) {
            txtNic.setForeground(Color.WHITE);
        } else {
            // JOptionPane.showMessageDialog(this, id);
            txtNic.setForeground(Color.RED);
        }
        BirthDetails birthDetails = new BirthDetails(txtNic.getText());
        String age = birthDetails.getAge();
        String birthDay = birthDetails.getBirthDay();
        String gender = birthDetails.getGender();

        System.out.println(age + " " + birthDay + " " + gender);
        spinAge.setValue(Integer.parseInt(age));
        txtDob.setText(birthDay);
        if (gender.equals("female")) {
            rbFemale.setSelected(true);
        } else {
            rbMale.setSelected(true);
        }
    }//GEN-LAST:event_txtNicActionPerformed

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicKeyReleased

    private void lblModfyEventBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBtMouseEntered

        lblModfyEventBt.setBorder(new LineBorder(new Color(43, 217, 127)));
    }//GEN-LAST:event_lblModfyEventBtMouseEntered

    private void lblModfyEventBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBtMouseExited

        lblModfyEventBt.setBorder(new LineBorder(Color.white));
    }//GEN-LAST:event_lblModfyEventBtMouseExited

    private void lblCancleEventBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBtMouseClicked

    }//GEN-LAST:event_lblCancleEventBtMouseClicked

    private void lblCancleEventBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBtMouseEntered

        lblCancleEventBt.setBorder(new LineBorder(new Color(43, 217, 127)));
    }//GEN-LAST:event_lblCancleEventBtMouseEntered

    private void lblCancleEventBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBtMouseExited

        lblCancleEventBt.setBorder(new LineBorder(Color.white));
    }//GEN-LAST:event_lblCancleEventBtMouseExited

    private void lblModfyEventBt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseClicked
        SettingsPanel s = new SettingsPanel();
        homeFrame.panelBody.removeAll();
        s.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.add(s);
        homeFrame.panelBody.revalidate();
        homeFrame.panelBody.repaint();
    }//GEN-LAST:event_lblModfyEventBt1MouseClicked

    private void lblModfyEventBt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt1MouseEntered

    private void lblModfyEventBt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt1MouseExited

    private void txtFname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname1KeyPressed

    private void txtFname1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname1KeyReleased

    private void lblModfyEventBt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt2MouseEntered

    private void lblModfyEventBt2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt2MouseExited

    private void lblCancleEventBt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancleEventBt1MouseClicked

    private void lblCancleEventBt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBt1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancleEventBt1MouseEntered

    private void lblCancleEventBt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBt1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancleEventBt1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel camPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCancleEventBt;
    private javax.swing.JLabel lblCancleEventBt1;
    private javax.swing.JLabel lblModfyEventBt;
    private javax.swing.JLabel lblModfyEventBt1;
    private javax.swing.JLabel lblModfyEventBt2;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JSpinner spinAge;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFb;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtFname1;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtOcc;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
