/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.werzuo.shfcms.common.BirthDetails;
import com.werzuo.shfcms.common.IDGenarator;
import com.werzuo.shfcms.common.Validation;
import com.werzuo.shfcms.model.Member;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author Ravindu
 */
public class MemberRegPanel extends javax.swing.JPanel {

    private HomeFrame homeFrame;
    private Dimension ds = new Dimension(320, 210);
    private Dimension cs = WebcamResolution.VGA.getSize();
    private Webcam wCam = Webcam.getDefault();
    private WebcamPanel wCamPanel = new WebcamPanel(wCam, ds, false);
    private String pic;

    public MemberRegPanel() {
        initComponents();

    }

    public MemberRegPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
        wCam.setViewSize(cs);
        wCamPanel.setFillArea(true);
        camPanel.setLayout(new FlowLayout());
        camPanel.add(wCamPanel);
        opencam();
        setUI();
    }

    public void opencam() {
        Thread thr = new Thread() {
            @Override
            public void run() {
                wCamPanel.start();

            }
        };
        thr.setDaemon(true);
        thr.start();
    }

    public void stopcam() {
        Thread thr = new Thread() {
            @Override
            public void run() {
                wCamPanel.stop();

            }
        };
        thr.setDaemon(true);
        thr.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        camPanel = new javax.swing.JPanel();
        lblUserImage = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblCid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtOcc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        spinAge = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtFb = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 227, 117), 2));
        jPanel1.setLayout(null);

        camPanel.setBackground(new java.awt.Color(0, 0, 0));
        camPanel.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(camPanel);
        camPanel.setBounds(600, 70, 320, 210);

        lblUserImage.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblUserImage.setForeground(new java.awt.Color(255, 255, 255));
        lblUserImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117)));
        jPanel1.add(lblUserImage);
        lblUserImage.setBounds(590, 60, 340, 230);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(":");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(160, 460, 10, 24);

        lblCid.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        lblCid.setForeground(new java.awt.Color(255, 255, 255));
        lblCid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblCid);
        lblCid.setBounds(180, 60, 300, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Member ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 60, 100, 30);

        txtDob.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDob.setForeground(new java.awt.Color(255, 255, 255));
        txtDob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDob.setOpaque(false);
        jPanel1.add(txtDob);
        txtDob.setBounds(740, 390, 190, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 60, 10, 24);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("First Name");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 110, 110, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(160, 110, 10, 24);

        txtFname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname.setForeground(new java.awt.Color(255, 255, 255));
        txtFname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname.setOpaque(false);
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtFname);
        txtFname.setBounds(180, 110, 300, 30);

        txtLName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtLName.setForeground(new java.awt.Color(255, 255, 255));
        txtLName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtLName.setOpaque(false);
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtLName);
        txtLName.setBounds(180, 160, 300, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(160, 160, 10, 24);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Last Name");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 160, 100, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Phone no.");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(40, 210, 110, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(160, 210, 10, 24);

        txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhone.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPhone.setOpaque(false);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        jPanel1.add(txtPhone);
        txtPhone.setBounds(180, 210, 300, 30);

        txtOcc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtOcc.setForeground(new java.awt.Color(255, 255, 255));
        txtOcc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOcc.setCaretColor(new java.awt.Color(255, 255, 255));
        txtOcc.setOpaque(false);
        txtOcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOccKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOccKeyReleased(evt);
            }
        });
        jPanel1.add(txtOcc);
        txtOcc.setBounds(180, 260, 300, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(160, 260, 10, 24);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Occupation");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(40, 260, 100, 30);

        txtNic.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNic.setForeground(new java.awt.Color(255, 255, 255));
        txtNic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNic.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNic.setOpaque(false);
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });
        jPanel1.add(txtNic);
        txtNic.setBounds(180, 310, 300, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(160, 310, 10, 24);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("N.I.C.");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 310, 110, 30);

        spinAge.setOpaque(false);
        jPanel1.add(spinAge);
        spinAge.setBounds(740, 440, 190, 30);
        spinAge.setOpaque(false);
        spinAge.getEditor().setOpaque(false);
        ((JSpinner.DefaultEditor)spinAge.getEditor()).getTextField().setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Gender");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(590, 340, 100, 30);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText(":");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(710, 340, 10, 24);

        rbMale.setBackground(new Color(0,0,0,0));
        buttonGroup1.add(rbMale);
        rbMale.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        rbMale.setForeground(new java.awt.Color(255, 255, 255));
        rbMale.setText("Male");
        rbMale.setContentAreaFilled(false);
        jPanel1.add(rbMale);
        rbMale.setBounds(740, 340, 80, 33);

        buttonGroup1.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbFemale.setText("Female");
        rbFemale.setContentAreaFilled(false);
        jPanel1.add(rbFemale);
        rbFemale.setBounds(830, 340, 100, 33);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText(":");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(710, 390, 10, 24);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("D.O.B.");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(590, 390, 100, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText(":");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(710, 440, 10, 24);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Age");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(590, 440, 110, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Email");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(40, 510, 100, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(160, 510, 10, 24);

        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.setOpaque(false);
        jPanel1.add(txtEmail);
        txtEmail.setBounds(180, 510, 300, 30);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(670, 510, 120, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(810, 510, 120, 40);

        txtFb.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFb.setForeground(new java.awt.Color(255, 255, 255));
        txtFb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFb.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFb.setOpaque(false);
        jPanel1.add(txtFb);
        txtFb.setBounds(180, 460, 300, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Address");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(40, 360, 80, 30);

        jScrollPane1.setBackground(new Color(0,0,0,0));
        jScrollPane1.setOpaque(false);

        txtAddress.setBackground(new Color(0,0,0,0));
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setRows(3);
        txtAddress.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAddress.setOpaque(false);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 360, 300, 70);
        jScrollPane1.getViewport().setOpaque(false);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setText("Browse");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(700, 300, 110, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setText("Capture");
        jButton1.setOpaque(false);
        jPanel1.add(jButton1);
        jButton1.setBounds(820, 300, 110, 30);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(160, 360, 10, 24);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Facebook");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(40, 460, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 227, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Member Registration");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(700, 0, 270, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtFname);
        }
    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtLNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameKeyReleased

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.phoneNumber(txtPhone);
        }
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtOccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOccKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtOcc);
        }
    }//GEN-LAST:event_txtOccKeyReleased

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Member member = createMemberModel();
            if (member != null) {
                stopcam();
                RegMesurementPanel a = new RegMesurementPanel(homeFrame, member);
                homeFrame.panelBody.removeAll();
                a.setSize(homeFrame.panelBody.getSize());
                homeFrame.panelBody.add(a);
                homeFrame.panelBody.repaint();
                homeFrame.panelBody.revalidate();
            } else {
                JOptionPane.showMessageDialog(this, "Member added fail !");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MemberRegPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MemberRegPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        stopcam();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtFname);
        }
    }//GEN-LAST:event_txtFnameKeyPressed

    private void txtLNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtLName);
        }
    }//GEN-LAST:event_txtLNameKeyPressed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.phoneNumber(txtPhone);
        }
    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtOccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOccKeyPressed
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.name(txtOcc);
        }
    }//GEN-LAST:event_txtOccKeyPressed

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        String id = txtNic.getText();
        txtNic.setForeground(Color.WHITE);
        if (id.length() == 10 | id.length() == 12) {
            txtNic.setForeground(Color.WHITE);
        } else {
            // JOptionPane.showMessageDialog(this, id);
            txtNic.setForeground(Color.RED);
        }
        BirthDetails birthDetails = new BirthDetails(txtNic.getText());
        String age = birthDetails.getAge();
        String birthDay = birthDetails.getBirthDay();
        String gender = birthDetails.getGender();

        System.out.println(age + " " + birthDay + " " + gender);
        spinAge.setValue(Integer.parseInt(age));
        txtDob.setText(birthDay);
        if (gender.equals("female")) {
            rbFemale.setSelected(true);
        } else {
            rbMale.setSelected(true);
        }
    }//GEN-LAST:event_txtNicActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel camPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCid;
    private javax.swing.JLabel lblUserImage;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JSpinner spinAge;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFb;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtOcc;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    /**
     * add member to the database
     *
     * @return Member model
     * @throws ClassNotFoundException
     * @throws SQLException
     */
    private Member createMemberModel() throws ClassNotFoundException, SQLException {

        String cid = lblCid.getText();
        String fName = txtFname.getText();
        String lName = txtLName.getText();
        int phoneNo = Integer.parseInt(txtPhone.getText());
        String occupation = txtOcc.getText();
        String nic = txtNic.getText();
        String gender;
        if (rbFemale.isSelected()) {
            gender = "female";
        } else {
            gender = "male";
        }
        String dob = txtDob.getText();
        int age = Integer.parseInt(spinAge.getValue().toString());
        String email = txtEmail.getText();
        String address = txtAddress.getText();
        String facebook = txtFb.getText();

        Member member = new Member(cid, fName, lName, phoneNo, occupation, nic,
                gender, dob, age, email, address, facebook, pic);

        return member;
    }

    /**
     * set up the user interface
     */
    private void setUI() {
        try {
            String newID = IDGenarator.getNewID("member", "cid", "M");
            lblCid.setText(newID);
        } catch (SQLException ex) {
            Logger.getLogger(MemberRegPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MemberRegPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
