/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import com.werzuo.shfcms.controller.MemberController;
import com.werzuo.shfcms.controller.PaymentController;
import com.werzuo.shfcms.controllerfactoryimpl.ControllerFactoryImpl;
import com.werzuo.shfcms.model.Member;
import com.werzuo.shfcms.model.PaymentArrears;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ravindu
 */
public class PaymentArriousPanel extends javax.swing.JPanel {

    private DefaultTableModel dtm;
    private ArrayList<String> detailsList;
    /**
     * Creates new form PaymentArriousPanel
     */
    private HomeFrame homeFrame;

    public PaymentArriousPanel() {
        initComponents();
        dtm = (DefaultTableModel) tblMemberDetails.getModel();
        loadToTblMemberDetails();
        loadToArray();
    }

    public PaymentArriousPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
        dtm = (DefaultTableModel) tblMemberDetails.getModel();
        loadToTblMemberDetails();
        loadToArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMemberDetails = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMemberShipNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setLayout(null);

        tblMemberDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MemberShip No", "Member First Name", "Member Last tName ", "Amount"
            }
        ));
        tblMemberDetails.setRowHeight(25);
        tblMemberDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMemberDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMemberDetails);
        if (tblMemberDetails.getColumnModel().getColumnCount() > 0) {
            tblMemberDetails.getColumnModel().getColumn(0).setMinWidth(100);
            tblMemberDetails.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblMemberDetails.getColumnModel().getColumn(0).setMaxWidth(100);
            tblMemberDetails.getColumnModel().getColumn(3).setMinWidth(70);
            tblMemberDetails.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblMemberDetails.getColumnModel().getColumn(3).setMaxWidth(70);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 120, 540, 410);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Month", "Amount"
            }
        ));
        jTable3.setRowHeight(25);
        jTable3.setRowMargin(25);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(1).setMinWidth(80);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTable3.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        add(jScrollPane3);
        jScrollPane3.setBounds(640, 120, 280, 330);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Back");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        add(jLabel6);
        jLabel6.setBounds(700, 500, 100, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Payment");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel5);
        jLabel5.setBounds(820, 500, 100, 40);

        txtMemberShipNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMemberShipNo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMemberShipNo.setOpaque(false);
        txtMemberShipNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMemberShipNoActionPerformed(evt);
            }
        });
        txtMemberShipNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMemberShipNoKeyReleased(evt);
            }
        });
        add(txtMemberShipNo);
        txtMemberShipNo.setBounds(160, 80, 160, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Membeship No");
        add(jLabel4);
        jLabel4.setBounds(50, 74, 110, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 217, 127));
        jLabel2.setText("Payment Arrears");
        add(jLabel2);
        jLabel2.setBounds(780, 10, 178, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel3);
        jLabel3.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMemberShipNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMemberShipNoActionPerformed

    }//GEN-LAST:event_txtMemberShipNoActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        DashBoardPanel a = new DashBoardPanel(homeFrame);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_jLabel6MouseClicked
    private ArrayList<String> arrayList = new ArrayList<>();


    private void txtMemberShipNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemberShipNoKeyReleased
        String membershipNo = txtMemberShipNo.getText();
        loadToArray();
        for (String detailsList1 : detailsList) {
            String[] columnDataArray = detailsList1.split(",");
            String membId = columnDataArray[0];
            char[] toCharArray = membId.toCharArray();
            String asd = "";
            for (char u : toCharArray) {
                asd += u;
                if (asd.equals(membershipNo)) {
                    arrayList.add(detailsList1);
                }
            }
        }
        tblMemberDetails.removeAll();
        int size = arrayList.size();
        dtm.setRowCount(size);
        for (int i = 0; i < size; i++) {
            String data = arrayList.get(i);
            String[] split = data.split(",");
            Object[] os = {split[0], split[1], split[2], split[3]};
            dtm.addRow(os);
        }
    }//GEN-LAST:event_txtMemberShipNoKeyReleased

    private void tblMemberDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMemberDetailsMouseClicked

    }//GEN-LAST:event_tblMemberDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tblMemberDetails;
    private javax.swing.JTextField txtMemberShipNo;
    // End of variables declaration//GEN-END:variables

    /**
     * Get all payment arrears details from payment arrears sql table.It
     * returns, PaymentArrears model ArrayList.In for each loop get one by one
     * model then get cid from that model.After search from member sql table
     * using that cid, and get fName,lName.Again get all payment arrears and
     * find total arrears under that cid.Then check that cid exists on table.If
     * not exists add those data to table.
     */
    private void loadToTblMemberDetails() {
        try {
            PaymentController paymentController = new ControllerFactoryImpl().getPaymentController();
            ArrayList<PaymentArrears> viewAllNewPaymentArrears = paymentController.viewAllNewPaymentArrears();

            for (PaymentArrears viewAllNewPaymentArrear : viewAllNewPaymentArrears) {
                String pid = viewAllNewPaymentArrear.getPid();
                String cid = viewAllNewPaymentArrear.getCid();
                MemberController memberController = new ControllerFactoryImpl().getMemberController();
                Member searchMember = memberController.searchMember(cid);
                String fName = searchMember.getfName();
                String lName = searchMember.getlName();
                PaymentController paymentController1 = new ControllerFactoryImpl().getPaymentController();
                ArrayList<PaymentArrears> viewAllPaymentsArrearsByCid = paymentController1.viewAllPaymentsArrearsByCid(cid);
                double totalArrears = 0.0;
                for (PaymentArrears viewAllPaymentsArrearsByCid1 : viewAllPaymentsArrearsByCid) {
                    double arrears = viewAllPaymentsArrearsByCid1.getArrears();
                    totalArrears += arrears;
                }

                int rowCount = dtm.getRowCount();
                boolean ifTblExist = false;
                for (int i = 0; i < rowCount; i++) {
                    String tblCid = dtm.getValueAt(i, 1).toString();
                    if (cid.equals(tblCid)) {
                        ifTblExist = true;
                    }
                }
                if (ifTblExist != true) {
                    Object[] tblData = {cid, fName, lName, totalArrears};
                    dtm.addRow(tblData);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PaymentArriousPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PaymentArriousPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * Get all values exist on table's row wise and add data to detailsList
     * array.
     */
    private void loadToArray() {
        int rowCount = dtm.getRowCount();
        int columnCount = dtm.getColumnCount();
        for (int i = 0; i < rowCount; i++) {
            String allRowDetails = "";
            for (int j = 0; j < columnCount; j++) {
                String rowDetails = dtm.getValueAt(i, j).toString();
                allRowDetails += rowDetails + ",";
            }
            detailsList.add(allRowDetails);
        }
    }
}
