/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ravindu
 */
public class PaymentOptionPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentOptionPanel
     */
    private HomeFrame homeFrame;

    public PaymentOptionPanel() {
        initComponents();
    }

    public PaymentOptionPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame=homeFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtFname3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFname2 = new javax.swing.JTextField();
        lblModfyEventBt = new javax.swing.JLabel();
        lblCancleEventBt = new javax.swing.JLabel();
        lblCancleEventBt1 = new javax.swing.JLabel();
        lblModfyEventBt1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Payment Type Id", "Type", "Charge"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(150);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(490, 70, 400, 402);

        txtFname3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname3.setForeground(new java.awt.Color(255, 255, 255));
        txtFname3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname3.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname3.setOpaque(false);
        txtFname3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFname3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFname3KeyReleased(evt);
            }
        });
        add(txtFname3);
        txtFname3.setBounds(190, 180, 220, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Type");
        add(jLabel11);
        jLabel11.setBounds(50, 180, 100, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Charge");
        add(jLabel10);
        jLabel10.setBounds(50, 260, 100, 30);

        txtFname2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname2.setForeground(new java.awt.Color(255, 255, 255));
        txtFname2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname2.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname2.setOpaque(false);
        txtFname2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFname2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFname2KeyReleased(evt);
            }
        });
        add(txtFname2);
        txtFname2.setBounds(190, 260, 220, 30);

        lblModfyEventBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblModfyEventBt.setForeground(new java.awt.Color(255, 255, 255));
        lblModfyEventBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModfyEventBt.setText("Remove Charge");
        lblModfyEventBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblModfyEventBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModfyEventBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModfyEventBtMouseExited(evt);
            }
        });
        add(lblModfyEventBt);
        lblModfyEventBt.setBounds(50, 350, 130, 40);

        lblCancleEventBt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCancleEventBt.setForeground(new java.awt.Color(255, 255, 255));
        lblCancleEventBt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancleEventBt.setText("Modify Charge");
        lblCancleEventBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblCancleEventBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancleEventBtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancleEventBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancleEventBtMouseExited(evt);
            }
        });
        add(lblCancleEventBt);
        lblCancleEventBt.setBounds(200, 350, 130, 40);

        lblCancleEventBt1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCancleEventBt1.setForeground(new java.awt.Color(255, 255, 255));
        lblCancleEventBt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancleEventBt1.setText("Add new Charge");
        lblCancleEventBt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblCancleEventBt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancleEventBt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCancleEventBt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCancleEventBt1MouseExited(evt);
            }
        });
        add(lblCancleEventBt1);
        lblCancleEventBt1.setBounds(340, 350, 130, 40);

        lblModfyEventBt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblModfyEventBt1.setForeground(new java.awt.Color(255, 255, 255));
        lblModfyEventBt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModfyEventBt1.setText("Back");
        lblModfyEventBt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblModfyEventBt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseExited(evt);
            }
        });
        add(lblModfyEventBt1);
        lblModfyEventBt1.setBounds(810, 500, 120, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 227, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Payment Options");
        add(jLabel3);
        jLabel3.setBounds(700, 0, 270, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel2);
        jLabel2.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFname3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname3KeyPressed

    private void txtFname3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname3KeyReleased

    private void txtFname2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname2KeyPressed

    private void txtFname2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname2KeyReleased

    private void lblModfyEventBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBtMouseEntered

        lblModfyEventBt.setBorder(new LineBorder(new Color(43, 217, 127)));
    }//GEN-LAST:event_lblModfyEventBtMouseEntered

    private void lblModfyEventBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBtMouseExited

        lblModfyEventBt.setBorder(new LineBorder(Color.white));
    }//GEN-LAST:event_lblModfyEventBtMouseExited

    private void lblCancleEventBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBtMouseClicked

    }//GEN-LAST:event_lblCancleEventBtMouseClicked

    private void lblCancleEventBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBtMouseEntered

        lblCancleEventBt.setBorder(new LineBorder(new Color(43, 217, 127)));
    }//GEN-LAST:event_lblCancleEventBtMouseEntered

    private void lblCancleEventBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBtMouseExited

        lblCancleEventBt.setBorder(new LineBorder(Color.white));
    }//GEN-LAST:event_lblCancleEventBtMouseExited

    private void lblCancleEventBt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBt1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancleEventBt1MouseClicked

    private void lblCancleEventBt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBt1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancleEventBt1MouseEntered

    private void lblCancleEventBt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancleEventBt1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancleEventBt1MouseExited

    private void lblModfyEventBt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseClicked
        SettingsPanel s = new SettingsPanel();
        homeFrame.panelBody.removeAll();
        s.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.add(s);
        homeFrame.panelBody.revalidate();
        homeFrame.panelBody.repaint();
    }//GEN-LAST:event_lblModfyEventBt1MouseClicked

    private void lblModfyEventBt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt1MouseEntered

    private void lblModfyEventBt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCancleEventBt;
    private javax.swing.JLabel lblCancleEventBt1;
    private javax.swing.JLabel lblModfyEventBt;
    private javax.swing.JLabel lblModfyEventBt1;
    private javax.swing.JTextField txtFname2;
    private javax.swing.JTextField txtFname3;
    // End of variables declaration//GEN-END:variables
}
