/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ravindu
 */
public class PrintSettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrintSettingsPanel
     */
    private HomeFrame homeFrame;

    public PrintSettingsPanel() {
        initComponents();
    }

    public PrintSettingsPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JLabel();
        lblModfyEventBt1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtFname6 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFname5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFname4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        cardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 217, 127)));
        cardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        cardPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        add(cardPanel);
        cardPanel.setBounds(50, 160, 410, 230);

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdd.setText("Print");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(570, 340, 130, 40);

        btnAdd1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdd1.setText("Create");
        btnAdd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAdd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAdd1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdd1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdd1MouseExited(evt);
            }
        });
        add(btnAdd1);
        btnAdd1.setBounds(760, 340, 130, 40);

        lblModfyEventBt1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblModfyEventBt1.setForeground(new java.awt.Color(255, 255, 255));
        lblModfyEventBt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModfyEventBt1.setText("Back");
        lblModfyEventBt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblModfyEventBt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblModfyEventBt1MouseExited(evt);
            }
        });
        add(lblModfyEventBt1);
        lblModfyEventBt1.setBounds(810, 500, 120, 40);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("MemberShip Number");
        add(jLabel15);
        jLabel15.setBounds(480, 270, 160, 30);

        txtFname6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname6.setForeground(new java.awt.Color(255, 255, 255));
        txtFname6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname6.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname6.setOpaque(false);
        txtFname6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFname6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFname6KeyReleased(evt);
            }
        });
        add(txtFname6);
        txtFname6.setBounds(670, 270, 220, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tel");
        add(jLabel14);
        jLabel14.setBounds(480, 220, 100, 30);

        txtFname5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname5.setForeground(new java.awt.Color(255, 255, 255));
        txtFname5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname5.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname5.setOpaque(false);
        txtFname5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFname5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFname5KeyReleased(evt);
            }
        });
        add(txtFname5);
        txtFname5.setBounds(670, 220, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 227, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create Member Card");
        add(jLabel3);
        jLabel3.setBounds(690, 0, 270, 50);

        txtFname4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname4.setForeground(new java.awt.Color(255, 255, 255));
        txtFname4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname4.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname4.setOpaque(false);
        txtFname4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFname4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFname4KeyReleased(evt);
            }
        });
        add(txtFname4);
        txtFname4.setBounds(670, 170, 220, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("User Name");
        add(jLabel13);
        jLabel13.setBounds(480, 170, 100, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 217, 127)));
        add(jLabel5);
        jLabel5.setBounds(50, 160, 410, 230);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel2);
        jLabel2.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFname4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname4KeyPressed

    private void txtFname4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname4KeyReleased

    private void txtFname5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname5KeyPressed

    private void txtFname5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname5KeyReleased

    private void txtFname6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname6KeyPressed

    private void txtFname6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFname6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFname6KeyReleased

    private void lblModfyEventBt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseClicked
        SettingsPanel s = new SettingsPanel();
        homeFrame.panelBody.removeAll();
        s.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.add(s);
        homeFrame.panelBody.revalidate();
        homeFrame.panelBody.repaint();
    }//GEN-LAST:event_lblModfyEventBt1MouseClicked

    private void lblModfyEventBt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt1MouseEntered

    private void lblModfyEventBt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModfyEventBt1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblModfyEventBt1MouseExited

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        Toolkit tkp = cardPanel.getToolkit();
        JFrame frame = new JFrame();
        PrintJob pjp = tkp.getPrintJob(frame, null, null);
        Graphics g = pjp.getGraphics();
        cardPanel.print(g);
        g.dispose();
        pjp.end();
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setBorder(new LineBorder(new Color(43, 217, 127)));
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setBorder(new LineBorder(Color.white));
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAdd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1MouseClicked

    private void btnAdd1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1MouseEntered

    private void btnAdd1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdd1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdd1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnAdd1;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblModfyEventBt1;
    private javax.swing.JTextField txtFname4;
    private javax.swing.JTextField txtFname5;
    private javax.swing.JTextField txtFname6;
    // End of variables declaration//GEN-END:variables
}
