/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import com.werzuo.shfcms.model.Measurement;
import com.werzuo.shfcms.model.Member;
import com.werzuo.shfcms.model.RegDetails;

/**
 *
 * @author Ravindu
 */
public class RegMesurementPanel extends javax.swing.JPanel {

    /**
     * Creates new form MesurementPanel
     */
    private HomeFrame homeFrame;
    private Member member;

    public RegMesurementPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
    }

    RegMesurementPanel(HomeFrame homeFrame, Member member) {
        initComponents();
        this.homeFrame = homeFrame;
        this.member = member;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblLeftBicep = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtFat = new javax.swing.JTextField();
        txtFatWeight = new javax.swing.JTextField();
        txtLean = new javax.swing.JTextField();
        txtLeanWeight = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBack = new javax.swing.JTextField();
        txtAbs = new javax.swing.JTextField();
        txtTriceps = new javax.swing.JTextField();
        txtBiceps = new javax.swing.JTextField();
        txtRestingBP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRestingHR = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSpecial4 = new javax.swing.JLabel();
        lblSpecial2 = new javax.swing.JLabel();
        lblSpecial = new javax.swing.JLabel();
        lblSpecial1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/weist.png"))); // NOI18N
        add(jLabel28);
        jLabel28.setBounds(749, 242, 90, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/neck.png"))); // NOI18N
        add(jLabel27);
        jLabel27.setBounds(774, 110, 40, 20);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/forearmLeft.png"))); // NOI18N
        add(jLabel25);
        jLabel25.setBounds(660, 80, 50, 60);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/forearmRight.png"))); // NOI18N
        add(jLabel26);
        jLabel26.setBounds(869, 70, 50, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/abs_1.png"))); // NOI18N
        add(jLabel24);
        jLabel24.setBounds(748, 183, 90, 70);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/chest.png"))); // NOI18N
        add(jLabel23);
        jLabel23.setBounds(731, 117, 110, 70);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/thightLeft.png"))); // NOI18N
        add(jLabel21);
        jLabel21.setBounds(730, 302, 50, 100);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/thightRight.png"))); // NOI18N
        add(jLabel22);
        jLabel22.setBounds(799, 298, 60, 100);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/calfRight.png"))); // NOI18N
        add(jLabel20);
        jLabel20.setBounds(820, 390, 30, 80);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/trcepsRight.png"))); // NOI18N
        add(jLabel19);
        jLabel19.setBounds(841, 130, 70, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/bicepsRight.png"))); // NOI18N
        add(jLabel18);
        jLabel18.setBounds(842, 104, 60, 40);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/tricepsLeft.png"))); // NOI18N
        add(jLabel17);
        jLabel17.setBounds(671, 131, 60, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/calfLeft.png"))); // NOI18N
        add(jLabel16);
        jLabel16.setBounds(755, 389, 50, 80);

        lblLeftBicep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/bicepsLeft.png"))); // NOI18N
        add(lblLeftBicep);
        lblLeftBicep.setBounds(690, 111, 60, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(480, 510, 120, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/CaptainBaiceps.png"))); // NOI18N
        add(jLabel15);
        jLabel15.setBounds(660, 50, 300, 480);

        txtFat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFat.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFat.setOpaque(false);
        add(txtFat);
        txtFat.setBounds(450, 130, 140, 30);

        txtFatWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFatWeight.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFatWeight.setOpaque(false);
        add(txtFatWeight);
        txtFatWeight.setBounds(450, 170, 140, 30);

        txtLean.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLean.setCaretColor(new java.awt.Color(255, 255, 255));
        txtLean.setOpaque(false);
        add(txtLean);
        txtLean.setBounds(450, 210, 140, 30);

        txtLeanWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLeanWeight.setCaretColor(new java.awt.Color(255, 255, 255));
        txtLeanWeight.setOpaque(false);
        add(txtLeanWeight);
        txtLeanWeight.setBounds(450, 250, 140, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Age");
        add(jLabel29);
        jLabel29.setBounds(40, 60, 70, 20);

        txtAge.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtAge.setForeground(new java.awt.Color(255, 255, 255));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAge.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAge.setOpaque(false);
        add(txtAge);
        txtAge.setBounds(140, 60, 140, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lean Weight");
        add(jLabel11);
        jLabel11.setBounds(350, 250, 100, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Lean");
        add(jLabel12);
        jLabel12.setBounds(350, 220, 80, 20);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fat Weight");
        add(jLabel13);
        jLabel13.setBounds(350, 180, 70, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fat");
        add(jLabel14);
        jLabel14.setBounds(350, 140, 70, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Biceps");
        add(jLabel7);
        jLabel7.setBounds(40, 310, 70, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Triceps");
        add(jLabel8);
        jLabel8.setBounds(40, 350, 70, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Abs");
        add(jLabel9);
        jLabel9.setBounds(40, 390, 80, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Back");
        add(jLabel10);
        jLabel10.setBounds(40, 430, 70, 20);

        txtBack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBack.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBack.setOpaque(false);
        add(txtBack);
        txtBack.setBounds(140, 430, 140, 30);

        txtAbs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAbs.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAbs.setOpaque(false);
        add(txtAbs);
        txtAbs.setBounds(140, 390, 140, 30);

        txtTriceps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTriceps.setCaretColor(new java.awt.Color(255, 255, 255));
        txtTriceps.setOpaque(false);
        add(txtTriceps);
        txtTriceps.setBounds(140, 350, 140, 30);

        txtBiceps.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtBiceps.setCaretColor(new java.awt.Color(255, 255, 255));
        txtBiceps.setOpaque(false);
        add(txtBiceps);
        txtBiceps.setBounds(140, 310, 140, 30);

        txtRestingBP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRestingBP.setCaretColor(new java.awt.Color(255, 255, 255));
        txtRestingBP.setOpaque(false);
        add(txtRestingBP);
        txtRestingBP.setBounds(140, 260, 140, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Resting BP");
        add(jLabel5);
        jLabel5.setBounds(40, 270, 70, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Resting HR");
        add(jLabel6);
        jLabel6.setBounds(40, 230, 80, 20);

        txtRestingHR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtRestingHR.setCaretColor(new java.awt.Color(255, 255, 255));
        txtRestingHR.setOpaque(false);
        add(txtRestingHR);
        txtRestingHR.setBounds(140, 220, 140, 30);

        txtHeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHeight.setCaretColor(new java.awt.Color(255, 255, 255));
        txtHeight.setOpaque(false);
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });
        add(txtHeight);
        txtHeight.setBounds(140, 140, 140, 30);

        txtWeight.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtWeight.setForeground(new java.awt.Color(255, 255, 255));
        txtWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtWeight.setCaretColor(new java.awt.Color(255, 255, 255));
        txtWeight.setOpaque(false);
        add(txtWeight);
        txtWeight.setBounds(140, 100, 140, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Weight");
        add(jLabel4);
        jLabel4.setBounds(40, 100, 70, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Height");
        add(jLabel3);
        jLabel3.setBounds(40, 140, 70, 20);

        lblSpecial4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSpecial4.setForeground(new java.awt.Color(153, 0, 0));
        lblSpecial4.setText("lbs");
        add(lblSpecial4);
        lblSpecial4.setBounds(600, 250, 30, 30);

        lblSpecial2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSpecial2.setForeground(new java.awt.Color(153, 0, 0));
        lblSpecial2.setText("%");
        add(lblSpecial2);
        lblSpecial2.setBounds(600, 210, 30, 30);

        lblSpecial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSpecial.setForeground(new java.awt.Color(153, 0, 0));
        lblSpecial.setText("kg");
        add(lblSpecial);
        lblSpecial.setBounds(600, 170, 30, 30);

        lblSpecial1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSpecial1.setForeground(new java.awt.Color(153, 0, 0));
        lblSpecial1.setText("%");
        add(lblSpecial1);
        lblSpecial1.setBounds(600, 130, 30, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel2);
        jLabel2.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        RegDetails regDetails = createRegMeasurementModel();
        OtherMeasurementsPanel a = new OtherMeasurementsPanel(homeFrame, member, regDetails);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        setAdultBodyFat();
    }//GEN-LAST:event_txtHeightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblLeftBicep;
    private javax.swing.JLabel lblSpecial;
    private javax.swing.JLabel lblSpecial1;
    private javax.swing.JLabel lblSpecial2;
    private javax.swing.JLabel lblSpecial4;
    private javax.swing.JTextField txtAbs;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBack;
    private javax.swing.JTextField txtBiceps;
    private javax.swing.JTextField txtFat;
    private javax.swing.JTextField txtFatWeight;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLean;
    private javax.swing.JTextField txtLeanWeight;
    private javax.swing.JTextField txtRestingBP;
    private javax.swing.JTextField txtRestingHR;
    private javax.swing.JTextField txtTriceps;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

    /**
     * create the register details model created by SW96
     *
     * @return regDetails
     */
    private RegDetails createRegMeasurementModel() {
        String cid = member.getCid();
        String joinDate = HomeFrame.getDate();
        String expDate = "";
        double weight = Double.parseDouble(txtWeight.getText());
        double height = Double.parseDouble(txtHeight.getText());
        double restingHr = Double.parseDouble(txtRestingHR.getText());
        double restingBp = Double.parseDouble(txtRestingBP.getText());
        double biceps = Double.parseDouble(txtBiceps.getText());
        double triceps = Double.parseDouble(txtTriceps.getText());
        double abs = Double.parseDouble(txtAbs.getText());
        double fat = Double.parseDouble(txtFat.getText());
        double fatWeight = Double.parseDouble(txtFatWeight.getText());
        double back = Double.parseDouble(txtBack.getText());
        double lean = Double.parseDouble(txtLean.getText());
        double leanWeight = Double.parseDouble(txtLeanWeight.getText());

        RegDetails regDetails = new RegDetails(cid, joinDate, expDate, weight,
                height, restingHr, restingBp, biceps, triceps, abs, fat, fatWeight,
                back, lean, leanWeight);

        return regDetails;
    }

    /**
     * created by robin setting adult body fat percentage to textFields
     */
    public void setAdultBodyFat() {
        if (txtHeight.getText().isEmpty() || txtWeight.getText().isEmpty()) {

            Double weight = Double.parseDouble(txtWeight.getText());
            Double height = Double.parseDouble(txtHeight.getText());
            Double bmi = weight / (height * height);
            Double age = Double.parseDouble(txtAge.getText());
            Double adultBdyFat;
            if (member.getGender().equals("male")) {

                adultBdyFat = (102.0 * bmi) + (0.23 * age) - (10.8 * 1) - 5.4;
                System.out.println("@RegMeasurementPanel in Male" + adultBdyFat);
            } else {
                adultBdyFat = (102.0 * bmi) + (0.23 * age) - 5.4;
                System.out.println("@RegMeasurementPanel in Female" + adultBdyFat);
            }
            txtFat.setText(Double.toString(adultBdyFat));
        }else{
            
        }

    }
}
