/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.border.LineBorder;

/**
 *
 * @author kaushalya
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReortPanel
     */
    private HomeFrame homeFrame;
    public ReportPanel() {
        initComponents();
    }
    public ReportPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lblAttendence1 = new javax.swing.JLabel();
        lblInventry1 = new javax.swing.JLabel();
        lblCustomerDetails1 = new javax.swing.JLabel();
        lblMeasurementGrowth1 = new javax.swing.JLabel();
        lblStar = new javax.swing.JLabel();
        lblPayments1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(47, 227, 117), 2));
        setLayout(null);

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl1.setText("Payments");
        add(lbl1);
        lbl1.setBounds(230, 210, 150, 30);

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl2.setText("Growth");
        add(lbl2);
        lbl2.setBounds(410, 210, 150, 30);

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl3.setText("Inventory");
        add(lbl3);
        lbl3.setBounds(590, 210, 150, 30);

        lbl4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl4.setForeground(new java.awt.Color(255, 255, 255));
        lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl4.setText("Customer Details");
        add(lbl4);
        lbl4.setBounds(770, 210, 150, 30);

        lbl5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl5.setForeground(new java.awt.Color(255, 255, 255));
        lbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl5.setText("***********");
        add(lbl5);
        lbl5.setBounds(50, 410, 150, 30);

        lbl6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl6.setForeground(new java.awt.Color(255, 255, 255));
        lbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl6.setText("Attendence");
        add(lbl6);
        lbl6.setBounds(50, 210, 150, 30);

        lblAttendence1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAttendence1.setForeground(new java.awt.Color(255, 255, 255));
        lblAttendence1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAttendence1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/ReportAttendanceWhite.png"))); // NOI18N
        lblAttendence1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblAttendence1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAttendence1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAttendence1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAttendence1MouseExited(evt);
            }
        });
        add(lblAttendence1);
        lblAttendence1.setBounds(50, 70, 150, 170);

        lblInventry1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInventry1.setForeground(new java.awt.Color(255, 255, 255));
        lblInventry1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventry1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/ReportInventoryWhite.png"))); // NOI18N
        lblInventry1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblInventry1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInventry1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblInventry1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblInventry1MouseExited(evt);
            }
        });
        add(lblInventry1);
        lblInventry1.setBounds(590, 70, 150, 170);

        lblCustomerDetails1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCustomerDetails1.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomerDetails1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerDetails1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/ReportCustdetailsWhite.png"))); // NOI18N
        lblCustomerDetails1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblCustomerDetails1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomerDetails1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomerDetails1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomerDetails1MouseExited(evt);
            }
        });
        add(lblCustomerDetails1);
        lblCustomerDetails1.setBounds(770, 70, 150, 170);

        lblMeasurementGrowth1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMeasurementGrowth1.setForeground(new java.awt.Color(255, 255, 255));
        lblMeasurementGrowth1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMeasurementGrowth1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/ReportGrowthWhite.png"))); // NOI18N
        lblMeasurementGrowth1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblMeasurementGrowth1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMeasurementGrowth1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMeasurementGrowth1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMeasurementGrowth1MouseExited(evt);
            }
        });
        add(lblMeasurementGrowth1);
        lblMeasurementGrowth1.setBounds(410, 70, 150, 170);

        lblStar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblStar.setForeground(new java.awt.Color(255, 255, 255));
        lblStar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(lblStar);
        lblStar.setBounds(50, 270, 150, 170);

        lblPayments1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPayments1.setForeground(new java.awt.Color(255, 255, 255));
        lblPayments1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPayments1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/ReportPaymentWhite.png"))); // NOI18N
        lblPayments1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblPayments1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPayments1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPayments1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPayments1MouseExited(evt);
            }
        });
        add(lblPayments1);
        lblPayments1.setBounds(230, 70, 150, 170);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(43, 227, 117));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reports");
        add(jLabel3);
        jLabel3.setBounds(850, 0, 120, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel2);
        jLabel2.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAttendence1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendence1MouseEntered
        lblAttendence1.setBorder(new LineBorder(new Color(43, 227, 117)));
        lbl6.setForeground(new Color(43, 227, 117));
        lblAttendence1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportAttendanceGreen.png"));
    }//GEN-LAST:event_lblAttendence1MouseEntered

    private void lblInventry1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventry1MouseEntered
        lblInventry1.setBorder(new LineBorder(new Color(43, 227, 117)));
        lbl3.setForeground(new Color(43, 227, 117));
        lblInventry1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportInventoryGreen.png"));
    }//GEN-LAST:event_lblInventry1MouseEntered

    private void lblCustomerDetails1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerDetails1MouseEntered
        lblCustomerDetails1.setBorder(new LineBorder(new Color(43, 227, 117)));
        lbl4.setForeground(new Color(43, 227, 117));
        lblCustomerDetails1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportCustDetailsGreen.png"));
    }//GEN-LAST:event_lblCustomerDetails1MouseEntered

    private void lblMeasurementGrowth1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeasurementGrowth1MouseEntered
        lblMeasurementGrowth1.setBorder(new LineBorder(new Color(43, 227, 117)));
        lbl2.setForeground(new Color(43, 227, 117));
        lblMeasurementGrowth1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportGrowthGreen.png"));
    }//GEN-LAST:event_lblMeasurementGrowth1MouseEntered

    private void lblAttendence1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendence1MouseExited
        lblAttendence1.setBorder(new LineBorder(Color.WHITE));
        lbl6.setForeground(Color.WHITE);
        lblAttendence1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportAttendanceWhite.png"));
    }//GEN-LAST:event_lblAttendence1MouseExited

    private void lblPayments1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPayments1MouseEntered
       lblPayments1.setBorder(new LineBorder(new Color(43, 227, 117)));
        lbl1.setForeground(new Color(43, 227, 117));
        lblPayments1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportPaymentGreen.png"));
    }//GEN-LAST:event_lblPayments1MouseEntered

    private void lblPayments1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPayments1MouseExited
        lblPayments1.setBorder(new LineBorder(Color.WHITE));
        lbl1.setForeground(Color.WHITE);
        lblPayments1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportPaymentWhite.png"));
    }//GEN-LAST:event_lblPayments1MouseExited

    private void lblMeasurementGrowth1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeasurementGrowth1MouseExited
        lblMeasurementGrowth1.setBorder(new LineBorder(Color.WHITE));
        lbl2.setForeground(Color.WHITE);
        lblMeasurementGrowth1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportGrowthWhite.png"));
    }//GEN-LAST:event_lblMeasurementGrowth1MouseExited

    private void lblInventry1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventry1MouseExited
        lblInventry1.setBorder(new LineBorder(Color.WHITE));
        lbl3.setForeground(Color.WHITE);
        lblInventry1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportInventoryWhite.png"));
    }//GEN-LAST:event_lblInventry1MouseExited

    private void lblCustomerDetails1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerDetails1MouseExited
        lblCustomerDetails1.setBorder(new LineBorder(Color.WHITE));
        lbl4.setForeground(Color.WHITE);
        lblCustomerDetails1.setIcon(new ImageIcon("./src/com/werzuo/shfcms/images/ReportCustDetailsWhite.png"));
    }//GEN-LAST:event_lblCustomerDetails1MouseExited

    private void lblAttendence1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttendence1MouseClicked
        ReportAttendence a = new ReportAttendence();
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblAttendence1MouseClicked

    private void lblPayments1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPayments1MouseClicked
        ReportPayments a1 = new ReportPayments();
        homeFrame.panelBody.removeAll();
        a1.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a1);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblPayments1MouseClicked

    private void lblMeasurementGrowth1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMeasurementGrowth1MouseClicked
        ReportMeassurementGrowth a3 = new ReportMeassurementGrowth();
        homeFrame.panelBody.removeAll();
        a3.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a3);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblMeasurementGrowth1MouseClicked

    private void lblInventry1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInventry1MouseClicked
        ReportInventory a2 = new ReportInventory();
        homeFrame.panelBody.removeAll();
        a2.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a2);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblInventry1MouseClicked

    private void lblCustomerDetails1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomerDetails1MouseClicked
        ReportCustomerDetails a4 = new ReportCustomerDetails();
        homeFrame.panelBody.removeAll();
        a4.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a4);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_lblCustomerDetails1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lblAttendence1;
    private javax.swing.JLabel lblCustomerDetails1;
    private javax.swing.JLabel lblInventry1;
    private javax.swing.JLabel lblMeasurementGrowth1;
    private javax.swing.JLabel lblPayments1;
    private javax.swing.JLabel lblStar;
    // End of variables declaration//GEN-END:variables

}
