/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.werzuo.shfcms.view;

import com.werzuo.shfcms.controller.MemberController;
import com.werzuo.shfcms.controller.OtherMeasurementController;
import com.werzuo.shfcms.controller.UserController;
import com.werzuo.shfcms.controllerfactory.ControllerFactory;
import com.werzuo.shfcms.controllerfactoryimpl.ControllerFactoryImpl;
import com.werzuo.shfcms.model.Member;
import com.werzuo.shfcms.model.OtherMeasurement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.CheckBox;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import org.bridj.objc.IMP;

/**
 *
 * @author Ravindu
 */
public class SearchMemberPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchMemberPanel
     */
    private HomeFrame homeFrame;
    private ControllerFactory cf = new ControllerFactoryImpl();
    private ArrayList<JCheckBox> checkboxes = new ArrayList();

    public SearchMemberPanel() {
        initComponents();
        setCheckBox();
    }

    public SearchMemberPanel(HomeFrame homeFrame) {
        initComponents();
        this.homeFrame = homeFrame;
        setCheckBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cb7 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb10 = new javax.swing.JCheckBox();
        cb11 = new javax.swing.JCheckBox();
        cb6 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();
        cb8 = new javax.swing.JCheckBox();
        cb9 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtMid = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtOcc = new javax.swing.JTextField();
        txtNic = new javax.swing.JTextField();
        txtFb = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText(":");
        add(jLabel27);
        jLabel27.setBounds(820, 220, 10, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("D.O.B");
        add(jLabel28);
        jLabel28.setBounds(770, 220, 50, 30);

        txtDob.setEditable(false);
        txtDob.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtDob.setForeground(new java.awt.Color(255, 255, 255));
        txtDob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDob.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDob.setOpaque(false);
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        txtDob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDobKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDobKeyReleased(evt);
            }
        });
        add(txtDob);
        txtDob.setBounds(830, 220, 130, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(":");
        add(jLabel26);
        jLabel26.setBounds(820, 170, 10, 30);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Age");
        add(jLabel25);
        jLabel25.setBounds(770, 170, 40, 30);

        txtAge.setEditable(false);
        txtAge.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtAge.setForeground(new java.awt.Color(255, 255, 255));
        txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAge.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAge.setOpaque(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAgeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        add(txtAge);
        txtAge.setBounds(830, 170, 130, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Back");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        add(jLabel7);
        jLabel7.setBounds(770, 480, 90, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Next");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        add(jLabel6);
        jLabel6.setBounds(880, 480, 80, 40);

        cb7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb7.setForeground(new java.awt.Color(255, 255, 255));
        cb7.setText("Gain Weight");
        cb7.setEnabled(false);
        cb7.setOpaque(false);
        cb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb7ActionPerformed(evt);
            }
        });
        add(cb7);
        cb7.setBounds(510, 300, 160, 30);

        cb4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb4.setForeground(new java.awt.Color(255, 255, 255));
        cb4.setText("Imorove Flexibility");
        cb4.setEnabled(false);
        cb4.setOpaque(false);
        cb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb4ActionPerformed(evt);
            }
        });
        add(cb4);
        cb4.setBounds(510, 170, 160, 30);

        cb1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb1.setForeground(new java.awt.Color(255, 255, 255));
        cb1.setText("Imorove Strength");
        cb1.setEnabled(false);
        cb1.setOpaque(false);
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        add(cb1);
        cb1.setBounds(510, 50, 160, 23);

        cb2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb2.setForeground(new java.awt.Color(255, 255, 255));
        cb2.setText("Weight Loss");
        cb2.setEnabled(false);
        cb2.setOpaque(false);
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        add(cb2);
        cb2.setBounds(510, 90, 160, 23);

        cb3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb3.setForeground(new java.awt.Color(255, 255, 255));
        cb3.setText("Maintain Fitness Level");
        cb3.setEnabled(false);
        cb3.setOpaque(false);
        cb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb3ActionPerformed(evt);
            }
        });
        add(cb3);
        cb3.setBounds(510, 130, 180, 23);

        cb10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb10.setForeground(new java.awt.Color(255, 255, 255));
        cb10.setText("Improve Muscle Tone And Shape");
        cb10.setEnabled(false);
        cb10.setOpaque(false);
        cb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb10ActionPerformed(evt);
            }
        });
        add(cb10);
        cb10.setBounds(510, 430, 240, 23);

        cb11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb11.setForeground(new java.awt.Color(255, 255, 255));
        cb11.setText("Improve Cardiovascular Fintss");
        cb11.setEnabled(false);
        cb11.setOpaque(false);
        cb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb11ActionPerformed(evt);
            }
        });
        add(cb11);
        cb11.setBounds(510, 470, 230, 23);

        cb6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb6.setForeground(new java.awt.Color(255, 255, 255));
        cb6.setText("Improve Esting Habit");
        cb6.setEnabled(false);
        cb6.setOpaque(false);
        cb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb6ActionPerformed(evt);
            }
        });
        add(cb6);
        cb6.setBounds(510, 260, 160, 23);

        cb5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb5.setForeground(new java.awt.Color(255, 255, 255));
        cb5.setText("Improve Fitness Level");
        cb5.setEnabled(false);
        cb5.setOpaque(false);
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });
        add(cb5);
        cb5.setBounds(510, 220, 190, 23);

        cb8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb8.setForeground(new java.awt.Color(255, 255, 255));
        cb8.setText("Reduce Stress");
        cb8.setEnabled(false);
        cb8.setOpaque(false);
        cb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb8ActionPerformed(evt);
            }
        });
        add(cb8);
        cb8.setBounds(510, 350, 190, 23);

        cb9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cb9.setForeground(new java.awt.Color(255, 255, 255));
        cb9.setText("Rehabilitate Injury");
        cb9.setEnabled(false);
        cb9.setOpaque(false);
        cb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb9ActionPerformed(evt);
            }
        });
        add(cb9);
        cb9.setBounds(510, 390, 160, 23);

        jLabel5.setForeground(new java.awt.Color(43, 217, 127));
        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ReadLine Qestions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(43, 227, 117))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(480, 20, 280, 500);

        txtMid.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtMid.setForeground(new java.awt.Color(255, 255, 255));
        txtMid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMid.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMid.setOpaque(false);
        txtMid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMidActionPerformed(evt);
            }
        });
        txtMid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMidKeyReleased(evt);
            }
        });
        add(txtMid);
        txtMid.setBounds(180, 60, 240, 30);

        txtAddress.setEditable(false);
        txtAddress.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAddress.setCaretColor(new java.awt.Color(255, 255, 255));
        txtAddress.setOpaque(false);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });
        add(txtAddress);
        txtAddress.setBounds(180, 360, 240, 30);

        txtFname.setEditable(false);
        txtFname.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFname.setForeground(new java.awt.Color(255, 255, 255));
        txtFname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFname.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFname.setOpaque(false);
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
        });
        add(txtFname);
        txtFname.setBounds(180, 110, 240, 30);

        txtLName.setEditable(false);
        txtLName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtLName.setForeground(new java.awt.Color(255, 255, 255));
        txtLName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtLName.setOpaque(false);
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLNameKeyReleased(evt);
            }
        });
        add(txtLName);
        txtLName.setBounds(180, 160, 240, 30);

        txtPhone.setEditable(false);
        txtPhone.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtPhone.setForeground(new java.awt.Color(255, 255, 255));
        txtPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPhone.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPhone.setOpaque(false);
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        add(txtPhone);
        txtPhone.setBounds(180, 210, 240, 30);

        txtOcc.setEditable(false);
        txtOcc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtOcc.setForeground(new java.awt.Color(255, 255, 255));
        txtOcc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOcc.setCaretColor(new java.awt.Color(255, 255, 255));
        txtOcc.setOpaque(false);
        txtOcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOccKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOccKeyReleased(evt);
            }
        });
        add(txtOcc);
        txtOcc.setBounds(180, 260, 240, 30);

        txtNic.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtNic.setForeground(new java.awt.Color(255, 255, 255));
        txtNic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNic.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNic.setOpaque(false);
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNicKeyReleased(evt);
            }
        });
        add(txtNic);
        txtNic.setBounds(180, 310, 240, 30);

        txtFb.setEditable(false);
        txtFb.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtFb.setForeground(new java.awt.Color(255, 255, 255));
        txtFb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFb.setCaretColor(new java.awt.Color(255, 255, 255));
        txtFb.setOpaque(false);
        add(txtFb);
        txtFb.setBounds(180, 410, 240, 30);

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        txtEmail.setOpaque(false);
        add(txtEmail);
        txtEmail.setBounds(180, 460, 240, 30);

        jLabel4.setForeground(new java.awt.Color(43, 217, 127));
        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Member Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(43, 227, 117))); // NOI18N
        add(jLabel4);
        jLabel4.setBounds(20, 20, 420, 500);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Phone no.");
        add(jLabel17);
        jLabel17.setBounds(40, 210, 110, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Member ID");
        add(jLabel9);
        jLabel9.setBounds(40, 60, 100, 30);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Email");
        add(jLabel24);
        jLabel24.setBounds(40, 460, 100, 30);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Facebook");
        add(jLabel29);
        jLabel29.setBounds(40, 410, 100, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Last Name");
        add(jLabel13);
        jLabel13.setBounds(40, 160, 100, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Occupation");
        add(jLabel15);
        jLabel15.setBounds(40, 260, 100, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Address");
        add(jLabel30);
        jLabel30.setBounds(40, 360, 80, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("N.I.C.");
        add(jLabel20);
        jLabel20.setBounds(40, 310, 110, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("First Name");
        add(jLabel11);
        jLabel11.setBounds(40, 110, 110, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        add(jLabel10);
        jLabel10.setBounds(160, 60, 10, 24);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        add(jLabel12);
        jLabel12.setBounds(160, 110, 10, 24);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        add(jLabel14);
        jLabel14.setBounds(160, 160, 10, 24);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":");
        add(jLabel18);
        jLabel18.setBounds(160, 210, 10, 24);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":");
        add(jLabel16);
        jLabel16.setBounds(160, 260, 10, 24);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(":");
        add(jLabel19);
        jLabel19.setBounds(160, 310, 10, 24);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText(":");
        add(jLabel31);
        jLabel31.setBounds(160, 360, 10, 24);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText(":");
        add(jLabel32);
        jLabel32.setBounds(160, 410, 10, 24);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText(":");
        add(jLabel23);
        jLabel23.setBounds(160, 460, 10, 24);

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(jLabel2);
        jLabel2.setBounds(800, 20, 140, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/Untitled-1.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 227, 117), 2));
        add(jLabel3);
        jLabel3.setBounds(0, 0, 970, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/werzuo/shfcms/images/panelBody.PNG"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 570);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyPressed


    }//GEN-LAST:event_txtFnameKeyPressed

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased

    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtLNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyPressed

    }//GEN-LAST:event_txtLNameKeyPressed

    private void txtLNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLNameKeyReleased

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyPressed

    }//GEN-LAST:event_txtPhoneKeyPressed

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased

    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtOccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOccKeyPressed

    }//GEN-LAST:event_txtOccKeyPressed

    private void txtOccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOccKeyReleased

    }//GEN-LAST:event_txtOccKeyReleased

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        try {
            searchMember();
        } catch (SQLException ex) {
            Logger.getLogger(SearchMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtNicActionPerformed

    private void txtNicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicKeyReleased

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtMidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMidKeyPressed

    private void txtMidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMidKeyReleased

    private void cb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb7ActionPerformed

    private void cb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb4ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb3ActionPerformed

    private void cb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb10ActionPerformed

    private void cb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb11ActionPerformed

    private void cb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb6ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb5ActionPerformed

    private void cb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb8ActionPerformed

    private void cb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb9ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        String cid = txtMid.getText();
        SerchMemberPanel2 a = new SerchMemberPanel2(homeFrame, cid);
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        SearchMemberPanel a = new SearchMemberPanel();
        homeFrame.panelBody.removeAll();
        a.setSize(homeFrame.panelBody.getSize());
        homeFrame.panelBody.removeAll();
        homeFrame.panelBody.add(a);
        homeFrame.panelBody.repaint();
        homeFrame.panelBody.revalidate();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtMidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMidActionPerformed
        try {
            searchMember();
        } catch (SQLException ex) {
            Logger.getLogger(SearchMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchMemberPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMidActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyPressed

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtDobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDobKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobKeyPressed

    private void txtDobKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDobKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb10;
    private javax.swing.JCheckBox cb11;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JCheckBox cb6;
    private javax.swing.JCheckBox cb7;
    private javax.swing.JCheckBox cb8;
    private javax.swing.JCheckBox cb9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFb;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMid;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtOcc;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    /**
     * search a member
     *
     * @throws SQLException
     * @throws ClassNotFoundException
     */
    private void searchMember() throws SQLException, ClassNotFoundException {
        String searchID = txtMid.getText();
        String searchName = txtNic.getText();
        MemberController memberController
                = new ControllerFactoryImpl().getMemberController();
        Member searchedMember = memberController.searchMemberBoth(searchID, searchName);

        if (searchedMember != null) {
            txtMid.setText(searchedMember.getCid());
            txtFname.setText(searchedMember.getfName());
            txtLName.setText(searchedMember.getlName());
            txtPhone.setText(Integer.toString(searchedMember.getPhoneNo()));
            txtOcc.setText(searchedMember.getOccupation());
            txtNic.setText(searchedMember.getNic());
            txtAddress.setText(searchedMember.getAddress());
            txtFb.setText(searchedMember.getFacebook());
            txtEmail.setText(searchedMember.getEmail());
            txtAge.setText(Integer.toString(searchedMember.getAge()));
            txtDob.setText(searchedMember.getDob());
            jLabel2.setIcon(new ImageIcon(searchedMember.getPic()));

            setReadLineQuestions(searchID);
        } else {
            new OptionPaneAddedSuccess(homeFrame, true, "Member not Found..");
        }
    }

    /**
     * set up the questions
     *
     * @param cid
     * @throws ClassNotFoundException
     * @throws SQLException
     */
    private void setReadLineQuestions(String cid) throws ClassNotFoundException, SQLException {
        OtherMeasurementController otherMeasurementController
                = new ControllerFactoryImpl().getOtherMeasurementController();
        OtherMeasurement searchOtherMeasurment = otherMeasurementController.searchOtherMeasurment(cid);

        if (searchOtherMeasurment != null) {
            for (String goal : searchOtherMeasurment.getGoals()) {
                for (JCheckBox checkbox : checkboxes) {
                    if (checkbox.getText().equalsIgnoreCase(goal)) {
                        checkbox.setSelected(true);
                    }
                }
            }
        }
    }

    /**
     * set up the check boxes
     */
    private void setCheckBox() {
        checkboxes.add(cb1);
        checkboxes.add(cb2);
        checkboxes.add(cb3);
        checkboxes.add(cb4);
        checkboxes.add(cb5);
        checkboxes.add(cb6);
        checkboxes.add(cb7);
        checkboxes.add(cb8);
        checkboxes.add(cb9);
        checkboxes.add(cb10);
        checkboxes.add(cb11);
    }
}
